////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////


=== Format "Metadata" (Metadata-Serialization)

Metadata objects are defined for scenarios where a client only wants to access the metadata of an object, but not the value.
Metadata objects are used to reduce the payload response to a minimum and to avoid the recursive traversing through the data model when not needed.
In many cases, a client is not interested in each child element or value of a resource, but only in the resource itself.

A metadata object does not contain any additional fields in relation to its full object representation, only some fields are left off.
The left off fields are fields which could be requested by an own API call and may consist of a recursive or potentially large substructure.
The serialization of a metadata object is the same as for the original full object, but without the left off fields.

For elements in the metamodel that are not listed in the table no "Metadata"-serialization is available.

.Metadata Attributes
[%autowidth,width="100%",cols="48%,52%",options="header",]
|===
|*Class Name* |*Fields not available in metadata representation*
2+h|*Identifiables*
|AssetAdministrationShell |assetInformation, submodels
|Submodel |submodelElements
2+h|*SubmodelElements*
|SubmodelElementCollection |value
|SubmodelElementList |value
|Entity |statements, globalAssetId, specificAssetId
|BasicEventElement |observed
|Capability |--
|Operation |--
2+h|*DataElements*
|Property |value, valueId
|MultilanguageProperty |value, valueId
|Range |min, max
|ReferenceElement |value
|RelationshipElement |first, second
|AnnotatedRelationshipElement |first, second, annotations
|Blob |value, contentType
|File |value, contentType
|===

*Example*

The example shows a JSON serialization of an AssetAdministrationShell object in its full representation and how it looks like in a metadata representation.

====
Note: for editorial reasons, some fields which are the same for both representations are omitted.
====

.AssetAdministrationShell JSON Serialization Example
|===
a|
[source,json,linenums]
----
{
    "idShort": "TestAssetAdministrationShell",
    "description": [...],
    "id": "idTestAAS",
     ...
    "derivedFrom": {...}
    "assetInformation": {...},
    "submodels": [...]
}
----
|===

.AssetAdministrationShell Metadata JSON Serialization Example
|===
a|
[source,json,linenums]
----
{
  "idShort": "TestAssetAdministrationShell",
  "description": [...],
  "id": "idTestAAS",
  ...
  "derivedFrom": {...}
}
----
|===
