@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

!include classes/asset-administration-shell.puml
!include classes/asset-information.puml
!include classes/enum-asset-kind.puml
!include classes/specific-asset-id.puml
!include classes/submodel.puml
!include classes/qualifier.puml
!include classes/submodel-element.puml
!include classes/property.puml

note left of Property
  Exemplary Submodel Element
  "Property",
  other submodel element subtypes
  include operations, collections, files
  etc.
end note

skinparam packageStyle rectangle
package "External Concept Definitions"  {
    hide members
    object "<<external>>\nProperty Definition\nIEC 61360" as PropertyDefinition{
    }
}

AssetAdministrationShell ..> AssetInformation
AssetAdministrationShell -->"0..*" Submodel : submodel:ref
AssetAdministrationShell -->"0..1" AssetAdministrationShell : derivedFrom:ref
AssetInformation ..> AssetKind
AssetInformation ..> SpecificAssetId
Submodel ..> SubmodelElement
Submodel ..> Qualifier
SubmodelElement .> Qualifier
SubmodelElement <|-- Property
SubmodelElement ..> PropertyDefinition : <<external global reference>>
@enduml