@startuml
skinparam classAttributeIconSize 0

package Details_of_the_Asset_Administration_Shell_Part_1a [
  + Common
  + Core
  + Referencing
  + Environment
  + Types
  + Concept Descriptions
  + Data Specifications (Templates)
]

package Common [
  + AdministrativeInformation
  + Extension
  + h0_HasExtensions
  + h1_Referable
  + h2_Identifiable
  + h3_HasKind
  + h4_HasSemantics
  + h5_Qualifiable
  + h6_HasDataSpecification
  + Common Entities
]
package CommonEntities [
  + Qualifier
]

package Core [
  + AssetAdministrationShell
  + AssetInformation
  + SpecificAssetId
  + Submodel
  + SubmodelElement
  + Submodel Elements
]
package Referencing [
  + Key
  + Reference
  + KeyTypes
  + ReferenceTypes
  + Referencing - Enumerations
]
package Environment [
  + Environment
]
package ConceptDescriptions [
  + ConceptDescription
]
package Types [
  + Common Metamodel Types
  + Basic and Primitive Types
]


package CommonMetamodelTypes [
  + Simple Types
  + Extended Types
]

package SimpleTypes [
  + Base64Binary
  + duration
  + boolean
  + dateTime
  + string
]

package ExtendedTypes [
  + langString
]

package BasicAndPrimitiveTypes [
  + MessageTopicType
  + ContentType
  + KeyType
  + RangeType
  + Resource
  + LabelType
  + MultiLanguageNameType
  + MultiLanguageTextType
  + NameType
  + RevisionType
  + VersionType
  + BlobType
  + Identifier
  + LangStringSet
  + PathType
  + QualifierType
  + ValueDataType
  + DataTypeDefXsd Enumeration
  + DataTypeDefRdf Enumeration
  + Enumerations
]

package DataTypeDefRdfEnumeration [
  + DataTypeDefRdf
]

package DataTypeDefXsdEnumeration [
  + DataTypeDefXsd
]

package Enumerations [
  + AssetKind
  + EntityType
  + ModellingKind
  + QualifierKind
]

package SubmodelElements [
  + AnnotatedRelationshipElement
  + BasicEventElement
  + Blob
  + Capability
  + DataElement
  + Entity
  + EventElement
  + File
  + MultiLanguageProperty
  + Operation
  + Property
  + Range
  + ReferenceElement
  + RelationshipElement
  + SubmodelElementCollection
  + SubmodelElementList
  + Submodel Element Entities
]

package SubmodelElementEntities [
  + EventPayload
  + OperationVariable
  + Direction
  + StateOfEvent
]

package ReferencingEnumerations [
  + KeyTypes
  + AasIdentifiables
  + AasReferableNonIdentifiables
  + AasReferables
  + AasSubmodelElements
  + FragmentKeys
  + GenericFragmentKeys
  + GenericGloballyIdentifiables
  + GloballyIdentifiables
]

' Relationships
Details_of_the_Asset_Administration_Shell_Part_1a ..> Common : <import>
Common ..> CommonEntities : <import>

Details_of_the_Asset_Administration_Shell_Part_1a ..> Core : <import>
Core ..> SubmodelElements : <import>
SubmodelElements ..> SubmodelElementEntities : <import>

Details_of_the_Asset_Administration_Shell_Part_1a ..> Referencing : <import>
Referencing ..> ReferencingEnumerations : <import>

Details_of_the_Asset_Administration_Shell_Part_1a ..> Environment : <import>

Details_of_the_Asset_Administration_Shell_Part_1a ..> Types : <import>
Types ..> CommonMetamodelTypes : <import>
CommonMetamodelTypes ..> SimpleTypes: <import>
CommonMetamodelTypes ..> ExtendedTypes: <import>
Types ..> BasicAndPrimitiveTypes : <import>
BasicAndPrimitiveTypes ..> DataTypeDefRdfEnumeration : <import>
BasicAndPrimitiveTypes ..> DataTypeDefXsdEnumeration : <import>
BasicAndPrimitiveTypes ..> Enumerations : <import>

Details_of_the_Asset_Administration_Shell_Part_1a ..> ConceptDescriptions : <import>

@enduml
