@startuml
skinparam classAttributeIconSize 0

object "Details of the Asset Administration Shell - Part 1a V3.0RC03 (normative)" as Part1 {
  + Common
  + Core
  + Referencing
  + Environment
  + Types
  + Concept Descriptions
  + Data Specifications (Templates)
}

object Common {
  + AdministrativeInformation
  + Extension
  + h0_HasExtensions
  + h1_Referable
  + h2_Identifiable
  + h3_HasKind
  + h4_HasSemantics
  + h5_Qualifiable
  + h6_HasDataSpecification
  + Common Entities
}
object CommonEntities {
  + Qualifier
}

object Core {
  + AssetAdministrationShell
  + AssetInformation
  + SpecificAssetId
  + Submodel
  + SubmodelElement
  + Submodel Elements
}
object Referencing {
  + Key
  + Reference
  + KeyTypes
  + ReferenceTypes
  + Referencing - Enumerations
}
object Environment {
  + Environment
}
object "Concept Descriptions" as ConceptDescriptions {
  + ConceptDescription
}
object Types {
  + Common Metamodel Types
  + Basic and Primitive Types
}


object "Common Metamodel Types" as CommonMetamodelTypes {
  + Simple Types
  + Extended Types
}

object "SimpleTypes" as SimpleTypes {
  + Base64Binary
  + duration
  + boolean
  + dateTime
  + string
}

object "Extended Types" as ExtendedTypes {
  + langString
}

object "Basic and Primitive Types" as BasicAndPrimitiveTypes {
  + MessageTopicType
  + ContentType
  + KeyType
  + RangeType
  + Resource
  + LabelType
  + MultiLanguageNameType
  + MultiLanguageTextType
  + NameType
  + RevisionType
  + VersionType
  + BlobType
  + Identifier
  + LangStringSet
  + PathType
  + QualifierType
  + ValueDataType
  + DataTypeDefXsd Enumeration
  + DataTypeDefRdf Enumeration
  + Enumerations
}

object "DataTypeDefRdf Enumeration" as DataTypeDefRdfEnumeration {
  + DataTypeDefRdf
}

object "DataTypeDefXsd Enumeration" as DataTypeDefXsdEnumeration {
  + DataTypeDefXsd
}

object Enumerations {
  + AssetKind
  + EntityType
  + ModellingKind
  + QualifierKind
}

object "Submodel Elements" as SubmodelElements {
  + AnnotatedRelationshipElement
  + BasicEventElement
  + Blob
  + Capability
  + DataElement
  + Entity
  + EventElement
  + File
  + MultiLanguageProperty
  + Operation
  + Property
  + Range
  + ReferenceElement
  + RelationshipElement
  + SubmodelElementCollection
  + SubmodelElementList
  + Submodel Element Entities
}

object "Submodel Element Entities" as SubmodelElementEntities {
  + EventPayload
  + OperationVariable
  + Direction
  + StateOfEvent
}

object "Referencing - Enumerations" as ReferencingEnumerations {
  + KeyTypes
  + AasIdentifiables
  + AasReferableNonIdentifiables
  + AasReferables
  + AasSubmodelElements
  + FragmentKeys
  + GenericFragmentKeys
  + GenericGloballyIdentifiables
  + GloballyIdentifiables
}

' Relationships
Part1 ..> Common : <import>
Common ..> CommonEntities : <import>

Part1 ..> Core : <import>
Core ..> SubmodelElements : <import>
SubmodelElements ..> SubmodelElementEntities : <import>

Part1 ..> Referencing : <import>
Referencing ..> ReferencingEnumerations : <import>

Part1 ..> Environment : <import>

Part1 ..> Types : <import>
Types ..> CommonMetamodelTypes : <import>
CommonMetamodelTypes ..> SimpleTypes: <import>
CommonMetamodelTypes ..> ExtendedTypes: <import>
Types ..> BasicAndPrimitiveTypes : <import>
BasicAndPrimitiveTypes ..> DataTypeDefRdfEnumeration : <import>
BasicAndPrimitiveTypes ..> DataTypeDefXsdEnumeration : <import>
BasicAndPrimitiveTypes ..> Enumerations : <import>

Part1 ..> ConceptDescriptions : <import>

@enduml
