@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

!include classes/has-extension.puml
!include classes/referable.puml
!include classes/extension.puml

Extension -> "+refersTo" Referable:Reference
HasExtensions ..> Extension
HasExtensions <|-- Referable
@enduml