@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/


abstract class HasExtensions <<abstract>> {
  +extension: Extension[0..*]
}
abstract class Referable <<abstract>> {
  +category: NameType[0..1]
  +idShort: IdShortType[0..1]
  +displayName: MultiLanguageNameType[0..1]
  +description: MultiLanguageTextType[0..1]
}
class Extension<HasSemantics> {
  +name: NameType
  +valueType: DataTypeDefXsd[0..1]
  +value: ValueDataType[0..1]
  +refersTo: Reference[0..*]
}
Extension -> Referable: refersTo:ref
HasExtensions ..> Extension
HasExtensions <|-- Referable
@enduml