@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/
!include classes/has-kind.puml
!include classes/enum-modelling-kind.puml
HasKind .> ModellingKind
@enduml