@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

!include classes/asset-administration-shell.puml
!include classes/asset-information.puml
!include classes/submodel.puml

AssetAdministrationShell ..> AssetInformation
AssetAdministrationShell -->"+submodel 0..*" Submodel :Reference
AssetAdministrationShell -->"+derivedFrom 0..1" AssetAdministrationShell :Reference
@enduml