@startuml
skinparam classAttributeIconSize 0
hide methods

class RelationshipElement<SubmodelElement> {
  +first: Reference[0..1]
  +second: Reference[0..1]
}
class AnnotatedRelationshipElement {
  +annotation: DataElement[0..*]
}
RelationshipElement <|-- AnnotatedRelationshipElement
@enduml