@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/


abstract class DataElement<SubmodelElement> <<abstract>> {
}
class Property {
  +valueType: DataTypeDefXsd
  +value: ValueDataType[0..1]
  +valueId: Reference[0..1]
}
class MultiLanguageProperty {
  +value: MultiLanguageTextType[0..1]
  +valueId: Reference[0..1]
}
class Range <<Experimental>> {
  +valueType: DataTypeDefXsd
  +min: ValueDataType[0..1]
  +max: ValueDataType[0..1]
}
class Blob {
  +value: BlobType[0..1]
  +contentType: ContentType[0..1]
}
class File {
  +value: PathType[0..1]
  +contentType: ContentType[0..1]
}
class ReferenceElement {
  +value: Reference[0..1]
}
DataElement <|--- Blob
DataElement <|--- File
DataElement <|--- MultiLanguageProperty
DataElement <|-- Property
DataElement <|--- Range
DataElement <|-- ReferenceElement
@enduml