@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

!include classes/data-element.puml
!include classes/property.puml
!include classes/multi-language-property.puml
!include classes/range.puml
!include classes/blob.puml
!include classes/file.puml
!include classes/reference-element.puml

DataElement <|--- Blob
DataElement <|--- File
DataElement <|--- MultiLanguageProperty
DataElement <|-- Property
DataElement <|--- Range
DataElement <|-- ReferenceElement
@enduml