@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/


class Entity<SubmodelElement> {
  +statement: SubmodelElement[0..*]
  +entityType: EntityType[0..1]
  +globalAssetId: Identifier[0..1]
  +specificAssetId: SpecificAssetId[0..*]
}
enum EntityType <<enumeration>> {
  CoManagedEntity
  SelfManagedEntity
}
Entity .> EntityType
@enduml