@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/


class Operation<SubmodelElement> {
  +inputVariable: OperationVariable[0..*]
  +outputVariable: OperationVariable[0..*]
  +inoutputVariable: OperationVariable[0..*]
}
class OperationVariable {
  +value: SubmodelElement
}
Operation .> OperationVariable
@enduml