@startuml
skinparam classAttributeIconSize 0
hide methods

class Operation<SubmodelElement> {
  +inputVariable: OperationVariable[0..*]
  +outputVariable: OperationVariable[0..*]
  +inoutputVariable: OperationVariable[0..*]
}
class OperationVariable {
  +value: SubmodelElement
}
Operation .> OperationVariable
@enduml