@startuml
skinparam classAttributeIconSize 0
hide methods

class Key {
  +type: KeyTypes
  +value: Identifier
}
enum KeyTypes <<enumeration>> {
  AnnotatedRelationshipElement
  AssetAdministrationShell
  BasicEventElement
  Blob
  Capability
  ConceptDescription
  DataElement
  Entity
  EventElement
  File
  FragmentReference
  GlobalReference
  Identifiable
  MultiLanguageProperty
  Operation
  Property
  Range
  Referable
  ReferenceElement
  RelationshipElement
  Submodel
  SubmodelElement
  SubmodelElementCollection
  SubmodelElementList
}
Key .> KeyTypes
@enduml