@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/key.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/enum-aas-submodel-elements.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/enum-aas-identifiables.puml

enum KeyTypes <<enumeration>>

enum FragmentKeys <<enumeration>>

enum GenericFragmentKeys <<enumeration>> {
  FragmentReference
}

enum AasReferables <<enumeration>> {
  Referable
}

enum AasReferableNonIdentifiables <<enumeration>>

enum GloballyIdentifiables <<enumeration>>

enum GenericGloballyIdentifiables <<enumeration>> {
  GlobalReference
}

Key ..> KeyTypes
KeyTypes --|> FragmentKeys
KeyTypes --|> AasReferables
KeyTypes --|> GloballyIdentifiables
FragmentKeys --|> GenericFragmentKeys
FragmentKeys --|> AasReferableNonIdentifiables
AasReferables --|> AasReferableNonIdentifiables
AasReferables --|> AasIdentifiables
AasReferableNonIdentifiables --|> AasSubmodelElements
GloballyIdentifiables --|> AasIdentifiables
GloballyIdentifiables --|> GenericGloballyIdentifiables
@enduml