@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/


enum KeyTypes <<enumeration>> {
  AnnotatedRelationshipElement
  AssetAdministrationShell
  BasicEventElement
  Blob
  Capability
  ConceptDescription
  DataElement
  Entity
  EventElement
  File
  FragmentReference
  GlobalReference
  Identifiable
  MultiLanguageProperty
  Operation
  Property
  Range
  Referable
  ReferenceElement
  RelationshipElement
  Submodel
  SubmodelElement
  SubmodelElementCollection
  SubmodelElementList
}
@enduml