@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

!include classes/asset-administration-shell.puml
class AssetAdministrationShell {
  +administration: AdministrativeInformation[0..1]
  +id: Identifier
  +idShort: IdShortType[0..1]
  +displayName: MultiLanguageNameType[0..1]
  +description: MultiLanguageTextType[0..1]
  +extension: Extension[0..*]
  +embeddedDataSpecification: EmbeddedDataSpecification[0..*]
  +category: NameType[0..1] <<Deprecated>>
}

!include classes/asset-information.puml

!include classes/administrative-information.puml
class AdministrativeInformation {
  +embeddedDataSpecification: EmbeddedDataSpecification[0..*]
}

!include classes/enum-asset-kind.puml

!include classes/specific-asset-id.puml
class SpecificAssetId {
  +semanticId: Reference[0..1]
  +supplementalSemanticId: Reference[0..*]
}

!include classes/submodel.puml
class Submodel{
  +administration: AdministrativeInformation[0..1]
  +id: Identifier
  +idShort: IdShortType[0..1]
  +displayName: MultiLanguageNameType[0..1]
  +description: MultiLanguageTextType[0..1]
  +extension: Extension[0..*]
  +kind: ModellingKind[0..1]
  +semanticId: Reference[0..1]
  +supplementalSemanticId: Reference[0..*]
  +qualifier: Qualifier[0..*]
  +embeddedDataSpecification: EmbeddedDataSpecification[0..*]
  +category: NameType[0..1] <<Deprecated>>
}

!include classes/submodel-element.puml
abstract class SubmodelElement {
  +idShort: IdShortType[0..1]
  +displayName: MultiLanguageNameType[0..1]
  +description: MultiLanguageTextType[0..1]
  +extension: Extension[0..*]
  +semanticId: Reference[0..1]
  +supplementalSemanticId: Reference[0..*]
  +qualifier: Qualifier[0..*]
  +embeddedDataSpecification: EmbeddedDataSpecification[0..*]
  +category: NameType[0..1] <<Deprecated>>
}

!include classes/qualifier.puml
class Qualifier{
  +semanticId: Reference[0..1]
  +supplementalSemanticId: Reference[0..*]
}

!include classes/property.puml
class Property {
  +idShort: IdShortType[0..1]
  +displayName: MultiLanguageNameType[0..1]
  +description: MultiLanguageTextType[0..1]
  +extension: Extension[0..*]
  +semanticId: Reference[0..1]
  +supplementalSemanticId: Reference[0..*]
  +qualifier: Qualifier[0..*]
  +embeddedDataSpecification: EmbeddedDataSpecification[0..*]
  +category: NameType[0..1] <<Deprecated>>
}

note left of Property
  Exemplary Submodel Element
  "Property",
  other submodel element subtypes
  include operations, collections, files
  etc.
end note

package "External Concept Definitions"  {
    hide members
    object "<<external>>\nProperty Definition\nIEC 61360" as PropertyDefinition{
    }
}

AssetAdministrationShell ..> AssetInformation
AssetAdministrationShell ..> AdministrativeInformation
AssetAdministrationShell --->"submodel\n0..*" Submodel : Reference
AssetAdministrationShell -->"derivedFrom\n0..1" AssetAdministrationShell : Reference
AssetInformation ..> AssetKind
AssetInformation ..> SpecificAssetId
Submodel ..> AdministrativeInformation
Submodel ..> SubmodelElement
Submodel ..> Qualifier
SubmodelElement .> Qualifier
SubmodelElement <|-- Property
SubmodelElement ..> PropertyDefinition : <<external global reference>>
@enduml