@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/


!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/submodel-element.puml
abstract class SubmodelElement {
  .. ::Referable ..
  +idShort: IdShortType[0..1]
  +displayName: MultiLanguageNameType[0..1]
  +description: MultiLanguageTextType[0..1]
  +category: NameType[0..1] <<Deprecated>>
    .. ::HasExtensions ..
  +extension: Extension[0..*]
      .. ::HasSemantics ..
  +semanticId: Reference[0..1]
  +supplementalSemanticId: Reference[0..*]
        .. ::Qualifiable ..
  +qualifier: Qualifier[0..*]
        .. ::HasDataSpecification ..
  +dataSpecification: Reference[0..*]
}

!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/relationship-element.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/annotated-relationship-element.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/data-element.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/property.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/multi-language-property.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/range.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/blob.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/file.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/reference-element.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/capability.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/submodel-element-list.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/submodel-element-collection.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/entity.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/event-element.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/basic-event-element.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/operation.puml
!include https://raw.githubusercontent.com/admin-shell-io/aas-specs/IDTA-01001-3-1_working/documentation/IDTA-01001/modules/ROOT/partials/diagrams/classes/operation-variable.puml

AnnotatedRelationshipElement .> DataElement
DataElement <|--- Blob
DataElement <|-- File
DataElement <|--- MultiLanguageProperty
DataElement <|-- Property
DataElement <|-- Range
DataElement <|-- ReferenceElement
Entity ..> SubmodelElement
EventElement <|-- BasicEventElement
Operation ..> OperationVariable
OperationVariable ..> SubmodelElement
RelationshipElement <|-- AnnotatedRelationshipElement
SubmodelElement <|-- Capability
SubmodelElement <|-- DataElement
SubmodelElement <|--- Entity
SubmodelElement <|--- EventElement
SubmodelElement <|-- Operation
SubmodelElement <|--- RelationshipElement
SubmodelElement <|-- SubmodelElementCollection
SubmodelElement <|--- SubmodelElementList
SubmodelElementCollection ..> SubmodelElement
SubmodelElementList ..> SubmodelElement
@enduml