:page-partial:

= Summary and Outlook

This document has defined the metamodel for the structural viewpoint of the Asset Administration Shell using the technology-neutral modelling language UML.

Several serializations and mappings are offered for the Asset Administration Shell based on this specification:

* XML, mainly used for file exchange between partners via the exchange format _.aasx,_
* JSON, mainly used for API definition, but also for file exchange as alternative to XML, and
* RDF for reasoning.

Additional parts of the document series cover (see xref:IDTA-01xxx_Bibliography.adoc#bib37[[37\]]):

* interfaces and APIs for accessing the information of Asset Administration Shells (access, modify, query, and execute information and active functionality), Part 2; the payload of these APIs is based on the definitions of the information model in this document, Part 1,
* predefined data specification templates (Part 3 series), for example for concept descriptions of properties conformant to IEC61360 (Part 3a),
* the infrastructure, which hosts and interconnects multiple Asset Administration Shells, implementing registry, discovery services, endpoint handling, and more,
* security aspects including access control, Part 4.

