== Specification of the Asset Administration Shell
= Part 1: Metamodel (IDTA-01001)

====
This specification is part of the https://industrialdigitaltwin.org/en/content-hub/aasspecifications[Asset Administration Shell Specification series]
====

== Version
This is version 3.1 of the specification IDTA-01001.

Previous version: 3.0.1

== Notice

Publisher:  Industrial Digital Twin Association e.V. (IDTA)

IDTA Document Number: IDTA-01001-3-1

This work is licensed under a 
https://creativecommons.org/licenses/by/4.0/[Creative Commons Attribution 4.0 International License]. 

SPDX-License-Identifier: CC-BY-4.0

== How to Get in Contact

Contact: https://industrialdigitaltwin.org/en/contact[IDTA]

Sources: https://github.com/admin-shell-io/aas-specs[github]

Feedback:
* https://github.com/admin-shell-io/aas-specs/issues/new/choose[new issues, bugs

* https://github.com/admin-shell-io/questions-and-answers[Questions and Answers]   

== Editorial Notes

This document (version 3.1) was produced by the Work Stream "Specification of the Asset Administration Shell" of the Working Group "Open Technology" of the https://industrialdigitaltwin.org/[Industrial Digital Twin Association (IDTA)]. It is the first version published as html document and maintained completely open source.

Version 3.0, a major release, was finalized from June 2022 to January 2023 by the joint sub working group "Asset Administration Shell" of the working group "Reference Architectures, Standards and Norms" of the Plattform Industrie 4.0 and the working group "Open Technology" of the Industrial Digital Twin Association (IDTA). It is the first release published by the Industrial Digital Twin Association.

A major change consists in splitting the overall document into four parts: Part 1 (this document) covers the core metamodel of the Asset Administration Shell, Part 5 covers the AASX package exchange format, Part 3 is a series that covers the predefined data specifications and Part 4 covers the security metamodel. Another major change is that the mapping rules for the different supported exchange formats (XML, JSON and RDF) are moved to the github repositories themselves that also contain the schemata. Part 2, the API Specification, was defined in a separate document from the very beginning.

Version 3.0RC02 was produced from November 2020 to May 2022 by the sub working group "Asset Administration Shell" of the joint working group of the Plattform Industrie 4.0 working group "Reference Architectures, Standards and Norms" and the "Open Technology" working group of the Industrial Digital Twin Association.

Version 3.0RC01 of this document, published in November 2020, was produced from November 2019 to November 2020 by the sub working group "Asset Administration Shell" of the Plattform Industrie 4.0 working group "Reference Architectures, Standards and Norms".

The second version V2.0 of this document was produced from August 2018 to November 2019 by the sub working group "Asset Administration Shell" of the Platform Industrie 4.0 working group "Reference Architectures, Standards and Norms". Version 2.0.l was published in May 2020.

The first version of this document was produced September 2017 to July 2018 by a joint working group with members from ZVEI SG "Models and Standards" and the Plattform Industrie 4.0 working group "Reference Architectures, Standards and Norms ". The document was subsequently validated by the platform’s working group "Reference Architectures, Standards and Norms".



For better readability the abbreviation "I4.0" is consistently used for "Industrie 4.0" in compound terms. The term "Industrie 4.0" continues to be used when standing on its own.

include::./shared/IDTA-01xxx_Versioning.adoc[]

include::./shared/IDTA-01xxx_Conformance.adoc[]


