////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

include::../includes/constraints.adoc[]

:page-partial:

[[spec-constraints]]
=  Constraints: Global Invariants

== Introduction

This clause documents constraints that represent global invariants, i.e. constraints that cannot be assigned to a single class.

In contrast, a class invariant is a constraint that must be true for all instances of a class at any time. They are documented as part of the class specification.

== Constraints for Referables and Identifiables

{aasd117}


====
Note: in other words (AASd-117), __idShort__ is mandatory for all __Referable__s except for referables being direct childs of __SubmodelElementList__s and for all __Identifiable__s.
====


{aasd120}

{aasd022}


====
Note: AASd-022 also means that __idShort__s of referables shall be matched sensitive to the case.
====


== Constraints for Qualifiers

{aasd021}

{aasd119}

{aasd129}

== Constraints for Extensions

{aasd077}

== Constraints for Asset-Related Information

{aasd116}


====
Note: AASd-116 is important to enable a generic search across global and specific asset IDs (e.g. in IDTA-01002-3-0 discovery operations like GetAllAssetLinksById). In the future the constraint might become more strict in stating that the name “globalAssetId” shall not be used as SpecificAssetId/name.
====


== Constraints for Types

{aasd130}

Constraint AASd-130 ensures that encoding and interoperability between different serializations is possible. See https://www.w3.org/TR/xml/#charsets for more information on XML Schema 1.0 string handling.