////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////
= Metamodel Specification Details: Designators

This clause specifies the classes of the metamodel in detail.
An overview is provided in Clause xref:spec-metamodel/overview.adoc[].
Annex xref:ROOT:annex/uml.adoc[] explains UML modelling together with the specifics used in this specification.
Annex D depicts the templates used to describe the classes and relationships.
Annex G shows some of the diagrams together with all their inherited attributes to give a complete overview.

To understand the specifications, it is crucial to understand the common attributes first (xref:spec-metamodel/common.adoc[]).
They are reused throughout the specifications of the other classes ("inherits from") and define important concepts like identifiable, qualifiable, etc.
They are abstract, i.e. there is no object instance of such classes.

The concept of referencing and how a reference is represented in the UML diagrams and the tables is explained in Clause xref:spec-metamodel/referencing.adoc[] and Annex xref:ROOT:annex/uml.adoc[].

Constraints that are no invariants of classes are specified in Clause xref:spec-metamodel/constraints.adoc[].
