////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////
= Environment Attributes
include::../includes/constraints.adoc[]

.Metamodel for Environment
[plantuml, 47-USE-PUML-12-INSTEAD, svg]
....
include::partial$diagrams/12-environment.puml[]
....


====
Note: _Environment_ is not an identifiable or referable element.
It is introduced to enable file transfer as well as serialization.
====

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Environment]]Environment
h|Explanation: 3+a|Container for the sets of different identifiables
h|Inherits from: 3+|xref:spec-metamodel/referencing.adoc#Reference[Reference]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Environment`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|assetAdministrationShell 3+| `\https://admin-shell.io/aas/3/1/Environment/assetAdministrationShells`
a|Asset Administration Shell |xref:spec-metamodel/core.adoc#AssetAdministrationShell[AssetAdministrationShell] |0..*

.2+e|submodel 3+| `\https://admin-shell.io/aas/3/1/Environment/submodels`
a|Submodel |xref:spec-metamodel/core.adoc#Submodel[Submodel] |0..*

.2+e|conceptDescription 3+| `\https://admin-shell.io/aas/3/1/Environment/conceptDescriptions`
a|Concept description |xref:spec-metamodel/concept-description.adoc#ConceptDescription[ConceptDescription] |0..*
|===
