////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

[[part1-specification]]
= Specification (normative)

This clause specifies the information metamodel of the Asset Administration Shell.

An overview of the metamodel of the Asset Administration Shell is given in Subclause xref:spec-metamodel/overview.adoc[].
Subclause xref:spec-metamodel/designators.adoc[] describes the classes and all their attributes in detail.

The legend of the UML diagrams and the table specification of the classes is explained in Annex xref:annex/uml-templates.adoc[] and Annex xref:annex/uml.adoc[].
Readers familiar with UML may skip xref:annex/uml.adoc#omg-uml-general[OMG UML General].
It is however recommended to have a look at the xref:annex/uml.adoc#omg-uml-specifics[specifics] used in this modelling, especially those on dealing with model references.

////
====
Note: an xmi representation of the UML model can be found in the repository "aas-specs" in the GitHub project admin-shell-io *xref:bibliography.adoc#bib51[[51\]]*: https://github.com/admin-shell-io/aas-specs/tree/master/schemas/xmi
====
////


////
//* xref:Spec/Metamodel_Introduction.adoc[Introduction]

* xref:Spec/Metamodel_Overview.adoc[Overview]

* xref:Spec/Metamodel_Designators.adoc[Designators]

* xref:Spec/Metamodel_Common.adoc[Common Attributes]

* xref:Spec/Metamodel_Core.adoc[Core Classes]

* xref:Spec/Metamodel_SubmodelElements.adoc[Submodel Element Types]

* xref:Spec/Metamodel_ConceptDescriptions.adoc[Concept Descriptions]

* xref:Spec/Metamodel_Environment.adoc[Environment]

* xref:Spec/Metamodel_Referencing.adoc[Referencing]

* xref:Spec/Metamodel_DataTypes.adoc[Data Types]

* xref:Spec/Metamodel_Constraints.adoc[Constraints]

////
