////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

include::../includes/constraints.adoc[]

:page-partial:


= Overview Metamodel of the Asset Administration Shell

This clause gives an overview of the main classes of the Asset Administration Shell (AAS) metamodel.

<<image-overview-metamodel-of-the-asset-administration-shell>> shows the main classes to describe a single Asset Administration Shell.

An Asset Administration Shell represents exactly one asset (xref:spec-metamodel/core.adoc#aas_attributes[AssetAdministrationShell/assetInformation]).
Type assets and instance assets are distinguished by the attribute xref:spec-metamodel/core.adoc#asset-information-attributes[AssetInformation/assetKind].
See Clause xref:spec-metamodel/core.adoc[Core Classes] for details.

====
Note: the UML modelling uses so-called abstract classes for denoting reused concepts like "HasSemantics", "Qualifiable" etc.
====

In case of an Asset Administration Shell of an instance asset, a reference to the Asset Administration Shell representing the corresponding type asset or another instance asset it was derived from may be added (xref:spec-metamodel/core.adoc#aas_attributes[AssetAdministrationShell/derivedFrom]).
The same holds true for the Asset Administration Shell of a type asset.
Types can also be derived from other types.

.Overview Metamodel of the Asset Administration Shell
[[image-overview-metamodel-of-the-asset-administration-shell]]
[plantuml, 11-asset-administration-shell, svg]
....
include::partial$diagrams/11-asset-administration-shell.puml[]
....


An asset may typically be represented by several different identification properties like the serial number, the manufacturer part ID or the different customer part IDs, its RFID code, etc.
Such external identifiers are defined as specific asset IDs (xref:spec-metamodel/core.adoc#asset-information-attributes[AssetInformation/specificAssetId]), each characterized by a user-defined name, a value, and the user domain (tenant, subject in Attribute Based Access Control).
See Clause xref:spec-metamodel/core.adoc#asset-information-attributes[Asset Information Attributes] for details.
Additionally, a global asset identifier should be assigned to the asset (xref:spec-metamodel/core.adoc#asset-information-attributes[AssetInformation/globalAssetId]) in the production and operation phase.

Asset Administration Shells, submodels and concept descriptions need to be globally uniquely identifiable (xref:spec-metamodel/common.adoc#identifiable-attributes[Identifiable]).
Other elements like properties only need to be referable within the model and thus only require a local identifier (_idShort_ from xref:spec-metamodel/common.adoc#referable-attributes[Referable]).
For details on identification, see Clause xref:general.adoc#identification-of-elements[Identification of Elements].

xref:spec-metamodel/core.adoc#submodel-attributes[Submodel]s consist of a set of submodel elements.
Submodel elements may be qualified by a so-called xref:spec-metamodel/common.adoc#qualifier-attributes[Qualifier].
There might be more than one qualifier per xref:spec-metamodel/common.adoc#qualifiable-attributes[Qualifiable].

There are different subtypes of submodel elements like properties, operations, lists, etc.
See Clause xref:spec-metamodel/submodel-elements.adoc[Overview of Submodel Element Types] for details.
A typical submodel element is shown in the overview figure: a property is a data element that has a value of simple type like string, date, etc.
Every data element is a submodel element (not visible in the figure but implicitly the case, since xref:spec-metamodel/submodel-elements.adoc#data-element-and-overview-of-data-element-types[DataElement]    is inheriting from xref:spec-metamodel/core.adoc#submodel-element-attributes[SubmodelElement]).
For details on properties, see Clause xref:spec-metamodel/submodel-elements.adoc#property-attributes[Property Attributes].

Every submodel element needs a semantic definition (_semanticId_ in xref:spec-metamodel/common.adoc#has-semantics-attributes[HasSemantics]) to have a well-defined meaning.
The submodel element might either refer directly to a corresponding semantic definition provided by an external reference (e.g. to an ECLASS or IEC CDD property definition), or it may indirectly reference a concept description (xref:spec-metamodel/concept-description.adoc[ConceptDescription]).
See Clause xref:general.adoc#matching-strategies[Matching Strategies] for matching strategies.

A concept description may be derived from another property definition of an external standard or another concept description (xref:spec-metamodel/concept-description.adoc[ConceptDescription/isCaseOf]). _isCaseOf_ is a more formal definition of _sourceOfDefinition_, which is just text.

====
Note: in this case, most of the attributes are redundant because they are defined in the external standard.
Attributes for information like _preferredName_, _unit_ etc. are added to increase usability.
Consistency w.r.t. the referenced submodel element definitions should be ensured by corresponding tooling.
====

If a concept description is not just a copy or refinement of an external standard, the provider of the Asset Administration Shell using this concept description shall be aware that an interoperability with other Asset Administration Shells cannot be ensured.

Data specification templates (xref:data-specifications.adoc#data-specification-template-attributes[DataSpecification]) can be used to define a named set of additional attributes (besides those predefined by the metamodel) for an element.
The data specification template following IEC 61360 is typically used for the concept description of properties, providing e.g. an attribute "preferredName".
The _\<<template>>_ dependency is used to denote recommended data specification templates.
See Clause xref:data-specifications.adoc[Data Specification Templates] for details.

Data specification templates like the template for IEC 61360 property definitions (Part 3a) are explicitly predefined and recommended to be used by Plattform Industrie 4.0.
See Clause xref:data-specifications.adoc[Data Specification Templates] for details.
If proprietary templates are used, interoperability with other Asset Administration Shells cannot be ensured.

Besides submodel elements including properties and concept descriptions, other identifiable elements may also use additional templates (xref:spec-metamodel/common.adoc#has-data-specification-attributes[HasDataSpecification]).
Data specification templates are selected at design time.

<<image-metamodel-package-overview>> gives a complete overview of all elements defined in the metamodel and specified in Clause xref:spec-metamodel/nav-spec.adoc[Specification].
The UML packages reflect the structure of Clause xref:spec-metamodel/designators.adoc[Metamodel Specification Details: Designators].
The elements of package "Core" are specified as first class citizens in Clause xref:spec-metamodel/core.adoc[Core Classes], except for their imported packages: the elements of package "SubmodelElements" are specified in Clause xref:spec-metamodel/submodel-elements.adoc[Overview of Submodel Element Types].
Elements of package "Common" are specified in Clause xref:spec-metamodel/common.adoc[Common Attributes].
The elements of package "Reference" are specified in Clause xref:spec-metamodel/referencing.adoc[Referencing in Asset Administration Shells].
Elements from package "Types" are specified in Clause xref:spec-metamodel/datatypes.adoc[Primitive and Simple Data Types].
The only package that is not listed is "Data Specifications (Templates)" because data specifications are handled differently.
Data specification templates are explained in Clause ref:data-specifications.adoc[Data Specification Templates].

====
Note: the abstract classes are numbered h0_, h1_, etc. (e.g. h1_Referable); their aliases however are defined without this prefix.
The reason for this naming is that no order for inherited classes can be defined in the tooling used for UML modelling (Enterprise Architect), since they are ordered alphabetically.
The order is important for some serializations (e.g. for XML).
====

.Metamodel Package Overview
[[image-metamodel-package-overview]]
[plantuml, 13-structure, svg]
....
include::partial$diagrams/13-structure.puml[]
....


<<image-metamodel-of-environment>> shows the so-called environment.
The environment’s purpose is to list all Asset Administration Shells, all submodels, and all concept descriptions – in other word, all identifiables within an ecosystem.

.Metamodel of Environment
[[image-metamodel-of-environment]]
[plantuml, 12-environment, svg]
....
include::partial$diagrams/12-environment.puml[]
....
