////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////
[#referencing-in-aas]
= Referencing in Asset Administration Shells
include::../includes/constraints.adoc[]

== Overview

Two kinds of references are distinguished: references to external objects or entities (external reference) and references to model elements of the same or another Asset Administration Shell (model reference).
Model references are also used for metamodel inherent relationships like submodels of an Asset Administration Shell (notation see Annex xref:ROOT:annex/uml-templates.adoc[]).

An external reference is a unique identifier.
The identifier can be a concatenation of different identifiers, representing e.g. an IRDI-Path.

====
Note: references should not be mixed up with locators.
Even URLs can be used as identifiers and do not necessarily describe a resource that can be accessed.
====

==  Reference Attributes

.Metamodel of Reference
[plantuml, 48-reference, svg]
....
include::partial$diagrams/48-reference.puml[]
....


See Clause xref:annex/general.adoc#matching-algorithm-for-references[Matching Algorithm for References] for reference matching.

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Reference]]Reference
h|Explanation: 3+a|
Reference to either a model element of the same or another Asset Administration Shell or to an external entity

A model reference is an ordered list of keys, each key referencing an element.
The complete list of keys may, for example, be concatenated to a path that gives unique access to an element.

An external reference is a reference to an external entity.


h|Inherits from: 3+|--
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Reference`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|type 3+| `\https://admin-shell.io/aas/3/1/Reference/type`
a|
Type of the reference

Denotes whether the reference is an external reference or a model reference

|xref:ReferenceTypes[ReferenceTypes]|1

.2+e|referredSemanticId 3+| `\https://admin-shell.io/aas/3/1/Reference/referredSemanticId`
a|
Expected semantic ID of the referenced model element (_Reference/type=ModelReference_); there typically is no semantic ID for the referenced object of external references _(Reference/type=ExternalReference)_.


====
Note 1: if Reference/referredSemanticId is defined, the semanticId of the model element referenced should have a matching semantic ID.
If this is not the case, a validator should raise a warning.
====



====
Note 2: it is recommended to use an external reference for the semantic ID expected from the referenced model element.
====


|xref:Reference[Reference] |0..1

.2+e|key \<<ordered>> 3+| `\https://admin-shell.io/aas/3/1/Reference/keys`
a|Unique reference in its name space |xref:Key[Key] |1..*
|===

{empty} +

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
|Enumeration: e|[[ReferenceTypes]]ReferenceTypes
h|Explanation: |Enumeration for denoting whether an element is an external or model reference
|Set of: |--
h|ID: | `\https://admin-shell.io/aas/3/1/ReferenceTypes`

.2+h|Literal h| ID
h|Explanation

.2+e|ExternalReference | `\https://admin-shell.io/aas/3/1/ReferenceTypes/ExternalReference`
a|External reference

.2+e|ModelReference | `\https://admin-shell.io/aas/3/1/ReferenceTypes/ModelReference`
a|Model reference
|===

== Key Attributes

.Metamodel of Keys
[plantuml, 49-key, svg]
....
include::partial$diagrams/49-key.puml[]
....


Keys are used to define references (xref:spec-metamodel/referencing.adoc#Reference[Reference]).




.Metamodel of KeyTypes Enumeration
[plantuml, 51-key-types, svg]
....
include::partial$diagrams/51-key-types.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Key]]Key
h|Explanation: 3+a|A key is a reference to an element by its ID
h|Inherits from: 3+|--
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Key`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|type 3+| `\https://admin-shell.io/aas/3/1/Key/type`
a|
Denotes which kind of entity is referenced

If _Key/type = GlobalReference,_ the key represents a reference to a source that can be globally identified.

If _Key/type = FragmentReference,_ the key represents a bookmark or a similar local identifier within its parent element as specified by the key that precedes this key.

In all other cases, the key references a model element of the same or another Asset Administration Shell.
The name of the model element is explicitly listed.

|xref:KeyTypes[KeyTypes]|1

.2+e|value 3+| `\https://admin-shell.io/aas/3/1/Key/value`
a|The key value, for example an IRDI or a URI or the xref:spec-metamodel/common.adoc#Referable[idShort] or any other fragment value |xref:spec-metamodel/datatypes.adoc#Identifier[Identifier] |1
|===

An example for using a _FragmentId_ as type of a key is a reference to an element within a file that is part of an Asset Administration Shell aasx package.

.Metamodel of AasSubmodelElements Enumeration
[plantuml, 52-aas-submodel-elements, svg]
....
include::partial$diagrams/52-aas-submodel-elements.puml[]
....

[[table-key-types]]
[.table-with-appendix-table]
[cols="30%h,70%"]
|===
|Enumeration: e|[[KeyTypes]]KeyTypes
h|Explanation: a|Enumeration of different key value types within a key
|Set of: |xref:FragmentKeys[FragmentKeys], xref:AasReferables[AasReferables], xref:spec-metamodel/referencing.adoc#GloballyIdentifiables[GloballyIdentifiables]
h|ID: | `\https://admin-shell.io/aas/3/1/KeyTypes`

.2+h|Literal h| ID
h|Explanation


.2+e|AnnotatedRelationshipElement | `\https://admin-shell.io/aas/3/1/KeyTypes/AnnotatedRelationshipElement`
a|Annotated relationship element

.2+e|AssetAdministrationShell | `\https://admin-shell.io/aas/3/1/KeyTypes/AssetAdministrationShell`
a|Asset Administration Shell

.2+e|BasicEventElement | `\https://admin-shell.io/aas/3/1/KeyTypes/BasicEventElement`
a|Basic event element

.2+e|Blob | `\https://admin-shell.io/aas/3/1/KeyTypes/Blob`
a|Blob

.2+e|Capability | `\https://admin-shell.io/aas/3/1/KeyTypes/Capability`
a|Capability

.2+e|ConceptDescription | `\https://admin-shell.io/aas/3/1/KeyTypes/ConceptDescription`
a|Concept Description


.2+e|DataElement | `\https://admin-shell.io/aas/3/1/KeyTypes/DataElement`
a|
Data Element


====
Note: data elements are abstract, i.e. if a key uses "DataElement", the reference may be a property, file, etc.
====


.2+e|Entity | `\https://admin-shell.io/aas/3/1/KeyTypes/Entity`
a|Entity

.2+e|EventElement | `\https://admin-shell.io/aas/3/1/KeyTypes/EventElement`
a|
Event


====
Note: event element is abstract.
====


.2+e|File | `\https://admin-shell.io/aas/3/1/KeyTypes/File`
a|File

.2+e|FragmentReference | `\https://admin-shell.io/aas/3/1/KeyTypes/FragmentReference`
a|Bookmark or a similar local identifier of a subordinate part of a primary resource

.2+e|GlobalReference | `\https://admin-shell.io/aas/3/1/KeyTypes/GlobalReference`
a|Global reference

.2+e|Identifiable | `\https://admin-shell.io/aas/3/1/KeyTypes/Identifiable`
a|
Identifiable


====
Note: identifiable is abstract, i.e. if a key uses "Identifiable" the reference may be an Asset Administration Shell, a submodel or a concept description.
====


.2+e|MultiLanguageProperty | `\https://admin-shell.io/aas/3/1/KeyTypes/MultiLanguageProperty`
a|Property with a value that can be provided in multiple languages

.2+e|Operation| `\https://admin-shell.io/aas/3/1/KeyTypes/Operation`
a|Operation

.2+e|Property | `\https://admin-shell.io/aas/3/1/KeyTypes/Property`
a|Property

.2+e|Range | `\https://admin-shell.io/aas/3/1/KeyTypes/Range`
a|Range with min and max

.2+e|Referable | `\https://admin-shell.io/aas/3/1/KeyTypes/Referable`
a|
====
Note: referables are abstract, i.e. if a key uses "Referable", the reference may be an Asset Administration Shell, a property, etc.
====

.2+e|ReferenceElement | `\https://admin-shell.io/aas/3/1/KeyTypes/ReferenceElement`
a|Reference

.2+e|RelationshipElement | `\https://admin-shell.io/aas/3/1/KeyTypes/RelationshipElement`
a|Relationship

.2+e|Submodel | `\https://admin-shell.io/aas/3/1/KeyTypes/Submodel`
a|Submodel

.2+e|SubmodelElement | `\https://admin-shell.io/aas/3/1/KeyTypes/SubmodelElement`
a|
Submodel element


====
Note: submodel elements are abstract, i.e. if a key uses "SubmodelElement", the reference may be a property, a submodel element list, an operation, etc.
====


.2+e|SubmodelElementCollection | `\https://admin-shell.io/aas/3/1/KeyTypes/SubmodelElementCollection`
a|Struct of submodel elements

.2+e|SubmodelElementList | `\https://admin-shell.io/aas/3/1/KeyTypes/SubmodelElementList`
a|List of submodel elements
|===

{empty} +

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[FragmentKeys]]FragmentKeys
h|Explanation: a|
Enumeration of different fragment key value types within a key


====
Note: not used as type but in constraints.
====


h|Set of: |xref:AasReferableNonIdentifiables[AasReferableNonIdentifiables], xref:GenericFragmentKeys[GenericFragmentKeys]
h|ID: | `\https://admin-shell.io/aas/3/1/FragmentKeys`


.2+h|Literal h| ID
h|Explanation


.2+e|AnnotatedRelationshipElement | `\https://admin-shell.io/aas/3/1/FragmentKeys/AnnotatedRelationshipElement`
a|Annotated relationship element


.2+e|BasicEventElement | `\https://admin-shell.io/aas/3/1/FragmentKeys/BasicEventElement`
a|Basic event element

.2+e|Blob | `\https://admin-shell.io/aas/3/1/FragmentKeys/Blob`
a|Blob

.2+e|Capability | `\https://admin-shell.io/aas/3/1/FragmentKeys/Capability`
a|Capability



.2+e|DataElement | `\https://admin-shell.io/aas/3/1/FragmentKeys/DataElement`
a|
Data Element


====
Note: data elements are abstract, i.e. if a key uses "DataElement", the reference may be a property, file, etc.
====


.2+e|Entity | `\https://admin-shell.io/aas/3/1/FragmentKeys/Entity`
a|Entity

.2+e|EventElement | `\https://admin-shell.io/aas/3/1/FragmentKeys/EventElement`
a|
Event


====
Note: event element is abstract.
====


.2+e|File | `\https://admin-shell.io/aas/3/1/FragmentKeys/File`
a|File

.2+e|FragmentReference | `\https://admin-shell.io/aas/3/1/FragmentKeys/FragmentReference`
a|Bookmark or a similar local identifier of a subordinate part of a primary resource


.2+e|MultiLanguageProperty | `\https://admin-shell.io/aas/3/1/FragmentKeys/MultiLanguageProperty`
a|Property with a value that can be provided in multiple languages

.2+e|Operation| `\https://admin-shell.io/aas/3/1/FragmentKeys/Operation`
a|Operation

.2+e|Property | `\https://admin-shell.io/aas/3/1/FragmentKeys/Property`
a|Property

.2+e|Range | `\https://admin-shell.io/aas/3/1/FragmentKeys/Range`
a|Range with min and max


.2+e|ReferenceElement | `\https://admin-shell.io/aas/3/1/FragmentKeys/ReferenceElement`
a|Reference

.2+e|RelationshipElement | `\https://admin-shell.io/aas/3/1/FragmentKeys/RelationshipElement`
a|Relationship


.2+e|SubmodelElement | `\https://admin-shell.io/aas/3/1/FragmentKeys/SubmodelElement`
a|
Submodel element


====
Note: submodel elements are abstract, i.e. if a key uses "SubmodelElement", the reference may be a property, a submodel element list, an operation, etc.
====


.2+e|SubmodelElementCollection | `\https://admin-shell.io/aas/3/1/FragmentKeys/SubmodelElementCollection`
a|Struct of submodel elements

.2+e|SubmodelElementList | `\https://admin-shell.io/aas/3/1/FragmentKeys/SubmodelElementList`
a|List of submodel elements
|===

{empty} +

== Logical Enumerations 

<<model-for-refs-keys>> presents a logical model of key types.
These logical enumerations may be used to formulate constraints.

[#model-for-refs-keys]
.Logical Model for Keys of References (non-normative)
[plantuml, 50-key, svg]
....
include::partial$diagrams/50-key.puml[]
....

===  Logical Enumeration AasReferableNonIdentifiables

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[AasReferableNonIdentifiables]]AasReferableNonIdentifiables
h|Explanation: a|
Enumeration of different fragment key value types within a key


====
Note: not used as type but in constraints.
====


h|Set of: |xref:AasSubmodelElements[AasSubmodelElements]
h|ID: | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables`

.2+h|Literal h| ID
h|Explanation


.2+e|AnnotatedRelationshipElement | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/AnnotatedRelationshipElement`
a|Annotated relationship element


.2+e|BasicEventElement | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/BasicEventElement`
a|Basic event element

.2+e|Blob | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/Blob`
a|Blob

.2+e|Capability | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/Capability`
a|Capability


.2+e|DataElement | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/DataElement`
a|
Data Element


====
Note: data elements are abstract, i.e. if a key uses "DataElement", the reference may be a property, file, etc.
====


.2+e|Entity | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/Entity`
a|Entity

.2+e|EventElement | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/EventElement`
a|
Event


====
Note: event element is abstract.
====


.2+e|File | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/File`
a|File


.2+e|MultiLanguageProperty | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/MultiLanguageProperty`
a|Property with a value that can be provided in multiple languages

.2+e|Operation| `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Operation`
a|Operation

.2+e|Property | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/Property`
a|Property

.2+e|Range | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/Range`
a|Range with min and max


.2+e|ReferenceElement | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/ReferenceElement`
a|Reference

.2+e|RelationshipElement | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/RelationshipElement`
a|Relationship


.2+e|SubmodelElement | `\https://admin-shell.io/aas/3/1/AAasReferableNonIdentifiables/SubmodelElement`
a|
Submodel element


====
Note: submodel elements are abstract, i.e. if a key uses "SubmodelElement", the reference may be a property, a submodel element list, an operation, etc.
====


.2+e|SubmodelElementCollection | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/SubmodelElementCollection`
a|Struct of submodel elements

.2+e|SubmodelElementList | `\https://admin-shell.io/aas/3/1/AasReferableNonIdentifiables/SubmodelElementList`
a|List of submodel elements
|===

===  Logical Enumeration AasSubmodelElements

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[AasSubmodelElements]]AasSubmodelElements
h|Explanation: a|Enumeration of submodel element types including abstract submodel element types
h|Set of: | xref:AasContainerSubmodelElements[AasContainerSubmodelElements],  xref:AasNonContainerSubmodelElements[AasNonContainerSubmodelElements]
h|ID: | `\https://admin-shell.io/aas/3/1/AasSubmodelElements`

.2+h|Literal h| ID
h|Explanation


.2+e|AnnotatedRelationshipElement | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/AnnotatedRelationshipElement`
a|Annotated relationship element


.2+e|BasicEventElement | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/BasicEventElement`
a|Basic event element

.2+e|Blob | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Blob`
a|Blob

.2+e|Capability | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Capability`
a|Capability

.2+e|DataElement | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/DataElement`
a|
Data Element


====
Note: data elements are abstract, i.e. if a key uses "DataElement", the reference may be a property, file, etc.
====


.2+e|Entity | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Entity`
a|Entity

.2+e|EventElement | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/EventElement`
a|
Event


====
Note: event element is abstract.
====


.2+e|File | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/File`
a|File


.2+e|MultiLanguageProperty | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/MultiLanguageProperty`
a|Property with a value that can be provided in multiple languages

.2+e|Operation| `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Operation`
a|Operation

.2+e|Property | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Property`
a|Property

.2+e|Range | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Range`
a|Range with min and max



.2+e|ReferenceElement | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/ReferenceElement`
a|Reference

.2+e|RelationshipElement | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/RelationshipElement`
a|Relationship


.2+e|SubmodelElement | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/SubmodelElement`
a|
Submodel element


====
Note: submodel elements are abstract, i.e. if a key uses "SubmodelElement", the reference may be a property, a submodel element list, an operation, etc.
====


.2+e|SubmodelElementCollection | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/SubmodelElementCollection`
a|Struct of submodel elements

.2+e|SubmodelElementList | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/SubmodelElementList`
a|List of submodel elements
|===


===  Logical Enumeration AasNonContainerSubmodelElements




[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[AasNonContainerSubmodelElements]]AasNonContainerSubmodelElements
h|Explanation: a|Enumeration of non-container submodel element types including abstract submodel element types

====
Note: not used as type but may be used in constraints.
====

h|Set of: | --
h|ID: | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements`

.2+h|Literal h| ID
h|Explanation



.2+e|BasicEventElement | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/BasicEventElement`
a|Basic event element

.2+e|Blob | `\https://admin-shell.io/aas/3/1/AasSubmodelElements/Blob`
a|Blob

.2+e|Capability | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/Capability`
a|Capability


.2+e|DataElement | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/DataElement`
a|
Data Element


====
Note: data elements are abstract, i.e. if a key uses "DataElement", the reference may be a property, file, etc.
====


.2+e|EventElement | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/EventElement`
a|
Event


====
Note: event element is abstract.
====


.2+e|File | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/File`
a|File


.2+e|MultiLanguageProperty | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/MultiLanguageProperty`
a|Property with a value that can be provided in multiple languages

.2+e|Operation| `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/Operation`
a|Operation

.2+e|Property | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/Property`
a|Property

.2+e|Range | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/Range`
a|Range with min and max



.2+e|ReferenceElement | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/ReferenceElement`
a|Reference

.2+e|RelationshipElement | `\https://admin-shell.io/aas/3/1/AasNonContainerSubmodelElements/RelationshipElement`
a|Relationship


|===



===  Logical Enumeration AasContainerSubmodelElements


[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[AasContainerSubmodelElements]]AasContainerSubmodelElements
h|Explanation: a|Enumeration of conainer submodel element types including abstract container submodel element types

====
Note: not used as type but may be used in constraints.
====

h|Set of: | --
h|ID: | `\https://admin-shell.io/aas/3/1/AasContainerSubmodelElements`

.2+h|Literal h| ID
h|Explanation


.2+e|AnnotatedRelationshipElement | `\https://admin-shell.io/aas/3/1/AasContainerSubmodelElements/AnnotatedRelationshipElement`
a|Annotated relationship element


.2+e|Entity | `\https://admin-shell.io/aas/3/1/AasContainerSubmodelElements/Entity`
a|Entity


.2+e|SubmodelElementCollection | `\https://admin-shell.io/aas/3/1/AasContainerSubmodelElements/SubmodelElementCollection`
a|Struct of submodel elements

.2+e|SubmodelElementList | `\https://admin-shell.io/aas/3/1/AasContainerSubmodelElements/SubmodelElementList`
a|List of submodel elements
|===

===  Logical Enumeration AasReferables


[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[AasReferables]]AasReferables
h|Explanation: a|
Enumeration of referables


====
Note: not used as type but in constraints.
====


h|Set of: |xref:AasReferableNonIdentifiables[AasReferableNonIdentifiables], xref:AasIdentifiables[AasIdentifiables]
h|ID: | `\https://admin-shell.io/aas/3/1/AasReferables`

.2+h|Literal h| ID
h|Explanation


.2+e|AnnotatedRelationshipElement | `\https://admin-shell.io/aas/3/1/AasReferables/AnnotatedRelationshipElement`
a|Annotated relationship element

.2+e|AssetAdministrationShell | `\https://admin-shell.io/aas/3/1/AasReferables/AssetAdministrationShell`
a|Asset Administration Shell

.2+e|BasicEventElement | `\https://admin-shell.io/aas/3/1/AasReferables/BasicEventElement`
a|Basic event element

.2+e|Blob | `\https://admin-shell.io/aas/3/1/AasReferables/Blob`
a|Blob

.2+e|Capability | `\https://admin-shell.io/aas/3/1/AasReferables/Capability`
a|Capability

.2+e|ConceptDescription | `\https://admin-shell.io/aas/3/1/AasReferables/ConceptDescription`
a|
Concept description


.2+e|DataElement | `\https://admin-shell.io/aas/3/1/AasReferables/DataElement`
a|
Data element


====
Note: data elements are abstract, i.e. if a key uses "DataElement", the reference may be a property, file, etc.
====


.2+e|Entity | `\https://admin-shell.io/aas/3/1/AasReferables/Entity`
a|Entity

.2+e|EventElement | `\https://admin-shell.io/aas/3/1/AasReferables/EventElement`
a|
Event


====
Note: event element is abstract.
====


.2+e|File | `\https://admin-shell.io/aas/3/1/AasReferables/File`
a|File


.2+e|Identifiable | `\https://admin-shell.io/aas/3/1/AasReferables/Identifiable`
a|
Identifiable
====
Note: identifiables are abstract, i.e. if a key uses "Identifiable", the reference may be an Asset Administration Shell, a concept description, etc.
====

.2+e|MultiLanguageProperty | `\https://admin-shell.io/aas/3/1/AasReferables/MultiLanguageProperty`
a|Property with a value that can be provided in multiple languages

.2+e|Operation| `\https://admin-shell.io/aas/3/1/AasReferables/Operation`
a|Operation

.2+e|Property | `\https://admin-shell.io/aas/3/1/AasReferables/Property`
a|Property

.2+e|Range | `\https://admin-shell.io/aas/3/1/AasReferables/Range`
a|Range with min and max

.2+e|Referable | `\https://admin-shell.io/aas/3/1/AasReferables/Referable`
a|
====
Note: referables are abstract, i.e. if a key uses "Referable", the reference may be an Asset Administration Shell, a property, etc.
====

.2+e|ReferenceElement | `\https://admin-shell.io/aas/3/1/AasReferables/ReferenceElement`
a|Reference

.2+e|RelationshipElement | `\https://admin-shell.io/aas/3/1/AasReferables/RelationshipElement`
a|Relationship

.2+e|Submodel | `\https://admin-shell.io/aas/3/1/AasReferables/Submodel`
a|
Submodel

.2+e|SubmodelElement | `\https://admin-shell.io/aas/3/1/AasReferables/SubmodelElement`
a|
Submodel element


====
Note: submodel elements are abstract, i.e. if a key uses "SubmodelElement", the reference may be a property, a submodel element list, an operation, etc.
====


.2+e|SubmodelElementCollection | `\https://admin-shell.io/aas/3/1/AasReferables/SubmodelElementCollection`
a|Struct of submodel elements

.2+e|SubmodelElementList | `\https://admin-shell.io/aas/3/1/AasReferables/SubmodelElementList`
a|List of submodel elements
|===

===  Logical Enumeration GenericFragmentKeys




[.table-with-appendix-table]
[cols="30%h,70%"]
|===
|Enumeration: e|[[GenericFragmentKeys]]GenericFragmentKeys
|Explanation: a|
Enumeration of generic fragment key value types within a key


====
Note: not used as type but in constraints.
====


|Set of: |--
h|ID: | `\https://admin-shell.io/aas/3/1/GenericFragmentKeys`

.2+h|Literal h| ID
h|Explanation

.2+e|FragmentReference | `\https://admin-shell.io/aas/3/1/GenericFragmentKeys/FragmentReference`
a|Bookmark or a similar local identifier of a subordinate part of a primary resource

|===

===  Logical Enumeration AasIdentifiables

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[AasIdentifiables]]AasIdentifiables
h|Explanation: a|
Enumeration of all metamodel element types that represent identifiables


====
Note: not used as type but in constraints.
====


h|Set of: |--
h|ID: | `\https://admin-shell.io/aas/3/1/AasIdentifiables`

.2+h|Literal h| ID
h|Explanation

.2+e|AssetAdministrationShell | `\https://admin-shell.io/aas/3/1/AasIdentifiables/AssetAdministrationShell`
a|Asset Administration Shell

.2+e|ConceptDescription | `\https://admin-shell.io/aas/3/1/AasIdentifiables/ConceptDescription`
a|Concept description

.2+e|Identifiable | `\https://admin-shell.io/aas/3/1/AasIdentifiables/Identifiable`
a|
Identifiable


====
Note: Identifiables are abstract, i.e. if a key uses "Identifiable", the reference may be an Asset Administration Shell, a submodel, or a concept description.
====


.2+e|Submodel | `\https://admin-shell.io/aas/3/1/AasIdentifiables/Submodel`
a|Submodel

|===

===  Logical Enumeration GenericGloballyIdentifiables


[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[GenericGloballyIdentifiables]]GenericGloballyIdentifiables
h|Explanation: a|Enumeration of different key value types within a key
h|Set of: |--
h|ID: | `\https://admin-shell.io/aas/3/1/GenericGloballyIdentifiables`

.2+h|Literal h| ID
h|Explanation

.2+e|GlobalReference | `\https://admin-shell.io/aas/3/1/GenericGloballyIdentifiables/GlobalReference`
a|Global reference

|===

===  Logical Enumeration GloballyIdentifiables


[.table-with-appendix-table]
[cols="30%h,70%"]
|===
h|Enumeration: e|[[GloballyIdentifiables]]GloballyIdentifiables
h|Explanation: a|Enumeration of globally identifiable elements
h|Set of: |`\https://admin-shell.io/aas/3/1/GenericGloballyIdentifiables`, `\https://admin-shell.io/aas/3/1/AasIdentifiables`
h|ID: | `\https://admin-shell.io/aas/3/1/GloballyIdentifiables`

.2+h|Literal h| ID
h|Explanation



.2+e|AssetAdministrationShell | `\https://admin-shell.io/aas/3/1/GloballyIdentifiables/AssetAdministrationShell`
a|Asset Administration Shell

.2+e|ConceptDescription | `\https://admin-shell.io/aas/3/1/GloballyIdentifiables/ConceptDescription`
a|Concept description

.2+e|GlobalReference | `\https://admin-shell.io/aas/3/1/GloballyIdentifiables/GlobalReference`
a|Global reference

.2+e|Identifiable | `\https://admin-shell.io/aas/3/1/GloballyIdentifiables/Identifiable`
a|
Identifiable


====
Note: Identifiables are abstract, i.e. if a key uses "Identifiable", the reference may be an Asset Administration Shell, a submodel, or a concept description.
====


.2+e|Submodel | `\https://admin-shell.io/aas/3/1/GloballyIdentifiables/Submodel`
a|Submodel

|===

{empty} +

[#constraints]
== Constraints for References
=== Constraints

{aasd121}

{aasd122}

{aasd123}

{aasd124}

{aasd125}

====
Note: constraint AASd-125 ensures that the shortest path is used.
====

{aasd126}

{aasd127}

====
Note: which kind of fragments are supported depends on the content type and the specification of allowed fragment identifiers for the corresponding resource referenced.
====

{aasd128}

[#examples-for-references]
=== Examples

In the following examples for valid und invalid model references and external references.
The notation follows the grammar as defined in Clause xref:mappings/mappings.adoc#reference-serialization[Text Serialization of Values of Type "Reference"]. 
In addition to the examples in xref:mappings/mappings.adoc#examples-reference-serialization[Examples for Text Serialization of Values of Type "Reference"] in this clause also the constraints as defined for references are taken into account.



[.underline]#Examples for valid references:#

[example]
....
(Submodel)https://example.com/aas/1/1/1234859590

[ModelRef](Submodel)https://example.com/aas/1/1/1234859590

(GlobalReference)https://example.com/specification.html

[ExternalRef](GlobalReference)https://example.com/specification.html
....



[.underline]#Examples for invalid references:#

[example]
....
[Submodel](GlobalReference)https://example.com/aas/1/1/1234859590
....

Key type "Submodel" is not a globally identifiable (see Constraint AASd-121).

[example]
....
[ExternalRef](Submodel)https://example.com/aas/1/1/1234859590
....

Key type "Submodel" is no generic globally identifiable (see Constraint AASd-122).


[example]
....
[ModelRef](GlobalReference)https://example.com/aas/1/1/1234859590
....

Key type "GlobalReference" is no AAS identifiable (see Constraint AASd-123). 
The last key type "GlobalReference" is neither a generic globally identifiable nor a generic fragment key (see Constraint AASd-124).





[.underline]#Examples for valid external references:#

[example]
....
(GlobalReference)https://example.com/ressource

(GlobalReference)0173-1#02-EXA123#001

(GlobalReference)https://example.com/specification.html (FragmentReference)Hints
....

====
Note:

[example]
....
(GlobalReference)https://example.com/specification.html (FragmentReference)Hints
....

represents the path with fragment identifier

[example]
....
https://example.com/specification.html#Hints
....
====



[.underline]#Examples for valid model references:#

[example]
....
(AssetAdministrationShell)https://example.com/aas/1/0/12348

(Submodel)https://example.com/aas/1/1/1234859590

(Submodel)https://example.com/aas/1/1/1234859590, (File)Specification

(ConceptDescription)0173-1#02-BAA120#008

(Submodel)https://example.com/aas/1/1/1234859590, (SubmodelElementList)Documents, (SubmodelElementCollection)0, (MultiLanguageProperty)Title

(Submodel)https://example.com/aas/1/1/1234859590, (SubmodelElementCollection)Manual, (MultiLanguageProperty)Title
....

====
Note:

[example]
....
(SubmodelElementList)0, (MultiLanguageProperty)Title
....

may be identical to

[example]
....
(SubmodelElementCollection)Manual, (MultiLanguageProperty)Title
....

semantically and content-wise.
The difference is that more than one document is allowed in the first submodel and thus a submodel element list is defined:
elements in a list are numbered.

====

[example]
....
(Submodel)https://example.com/aas/1/1/1234859590, (File)Specification, (FragmentReference)Hints
....

====
Note: assuming the file has the value using the absolute path

[example]
....
https://example.com/specification.html 
....

(and not a relative path), the first reference points to the same information as the global reference

[example]
....
(GlobalReference)https://example.com/specification.html, (FragmentReference)Hints
....

====

[example]
....
(Submodel)https://example.com/aas/1/1/1234859590, (Blob)Specification, (FragmentReference)Hints
....




[.underline]#Examples for invalid model references:#

[example]
....
(GlobalReference)https://example.com/aas/1/1/1234859590
....

This is an external reference but no model reference.


[example]
....
(Property)0173-1#02-BAA120#008
....

This reference does not start with the ID of an Identifiable, i.e. key type "Property" is no AAS identifiable (see Constraint AASd-123).
Additionally, the value is not a valid xref:spec-metamodel/common.adoc#Referable[idShort] for a Property submodel element since it contains special characters like "#" (see Constraint AASd-002).


[example]
....
[ModelRef](FragmentReference)Hints (Property)Temperature
....

Key "Property" is no generic fragment key and therefore fragment key "FragmentReference" is not allowed before (see Constraint AASd-126).



[example]
....
(Submodel)https://example.com/aas/1/1/1234859590, (EventElement)Event, (FragmentReference)Comment
....

This model reference is invalid because fragment references so far are only defined for "File" and "Blob" submodel elements (see Constraint AASd-127).


[example]
....
(AssetAdministrationShell)https://example.com/aas/1/0/12348, (Submodel)https://example.com/aas/1/1/1234859590, (Property)Temperature
....

This is not a valid model reference because key type "AssetAdministrationShell"  and "Submodel" are both global identifiables and there shall be only one (see Constraints AASd-125).


