////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////
= Overview of Submodel Element Types
include::../includes/constraints.adoc[]

.Metamodel Overview for Submodel Element Subtypes
[[image-28-submodel-element-subtypes]]
[plantuml, 28-submodel-element, svg]
....
include::partial$diagrams/28-submodel-element.puml[]
....


Submodel elements include data properties as well as operations, events and other elements needed to describe a model for an asset (see <<image-28-submodel-element-subtypes>>).

== General

All submodel elements including abstract classes like data elements are specified in alphabetical order.

====
Note: value-related attributes typically are optional to enable definition of Submodel Templates as well, i.e. xref:spec-metamodel/core.adoc#Submodel[Submodels]  with value of xref:spec-metamodel/common.adoc#HasKind[Submodel/kind] equal to xref:spec-metamodel/common.adoc#ModellingKind[Template].
====

[#annotated-relationship-element-attributes]
== Annotated Relationship Element Attributes

.Metamodel of Annotated Relationship Elements
[plantuml, 29-relationship-element, svg]
....
include::partial$diagrams/29-relationship-element.puml[]
....


An annotated relationship is a relationship similar to a ternary association in UML.
The semantics of the relationship is defined via the _semanticId_ of the _RelationshipElement_.
If this semantic definition requires additional information not contained in the _first_ or _second_ object referenced via the relationship, this information needs to be stored as annotation.

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[AnnotatedRelationshipElement]]AnnotatedRelationshipElement
h|Explanation: 3+a|An annotated relationship element is a relationship element that can be annotated with additional data elements.
h|Inherits from: 3+|xref:RelationshipElement[RelationshipElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/AnnotatedRelationshipElement`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|[[AnnotatedRelationshipElement-annotations]] annotation 3+| `\https://admin-shell.io/aas/3/1/AnnotatedRelationshipElement/annotations`
a|A data element that represents an annotation that holds for the relationship between the two elements |xref:DataElement[DataElement] |0..*
|===

[[basic-event-element-attributes]]
== Basic Event Element Attributes

.Metamodel of Basic Event Element
[plantuml, 30-basic-event-element, svg]
....
include::partial$diagrams/30-basic-event-element.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[BasicEventElement]]BasicEventElement \<<Experimental>>
h|Explanation: 3+a|A basic event element
h|Inherits from: 3+|xref:EventElement[EventElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|[[BasicEventElement-observed]]observed 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement`
a|Reference to a referable, e.g. a data element or a submodel that is being observed |ModelReference<xref:spec-metamodel/common.adoc#Referable[Referable]> |1

.2+e|[[BasicEventElement-direction]]direction 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement/direction`
a|
Direction of event

Can be \{ input, output }

|xref:Direction[Direction]|1

.2+e|[[BasicEventElement-state]]state 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement/state`
a|
State of event

Can be { on, off }

|xref:StateOfEvent[StateOfEvent]|1

.2+e|[[BasicEventElement-messageTopic]]messageTopic 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement/messageTopic`
a|Information for the outer message infrastructure to schedule the event for the respective communication channel. |xref:spec-metamodel/datatypes.adoc#MessageTopicType[MessageTopicType] |0..1

.2+e|[[BasicEventElement-messageBroker]]messageBroker 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement/messageBroker`
a|
Information about which outer message infrastructure shall handle messages for the _EventElement_; refers to a xref:spec-metamodel/core.adoc#Submodel[Submodel], xref:spec-metamodel/submodel-elements.adoc#SubmodelElementList[SubmodelElementList], xref:spec-metamodel/submodel-elements.adoc#SubmodelElementCollection[SubmodelElementCollection]  or xref:spec-metamodel/submodel-elements.adoc#entity-attributes[Entity], which contains xref:spec-metamodel/submodel-elements.adoc#DataElement[DataElements] describing the proprietary specification for the message broker


====
Note: this proprietary specification could be standardized by using respective submodels for different message infrastructure, e.g. OPC UA, MQTT or AMQP.
====


|ModelReference<xref:spec-metamodel/common.adoc#Referable[Referable]> |0..1

.2+e|[[BasicEventElement-lastUpdate]]lastUpdate 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement/lastUpdate`
a|Timestamp in UTC, when the last event was received (input direction) or sent (output direction) |xref:spec-metamodel/datatypes.adoc#DateTimeUtc[DateTimeUtc] |0..1

.2+e|[[BasicEventElement-minInterval]]minInterval 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement/minInterval`
a|
For input direction reports on the maximum frequency, the software entity behind the respective referable can handle input events.

For output events, the maximum frequency of outputting this event to an outer infrastructure is specified.

Might be not specified, i.e. if there is no minimum interval.

|duration |0..1

.2+e|[[BasicEventElement-maxInterval]]maxInterval 3+| `\https://admin-shell.io/aas/3/1/BasicEventElement/maxInterval`
a|
Not applicable for input direction

For output direction: maximum interval in time, the respective referable shall send an update of the status of the event, even if no other trigger condition for the event was not met.

Might not be specified, i.e. if there is no maximum interval.

|duration |0..1
|===

{empty} +

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
|Enumeration: e|[[Direction]]Direction \<<Experimental>>
h|Explanation: a|Direction
|Set of: |--
h|ID: | `\https://admin-shell.io/aas/3/1/Direction`

.2+h|Literal h| ID
h|Explanation

.2+e|[[Direction-input]]input | `\https://admin-shell.io/aas/3/1/Direction/input`
a|Input direction

.2+e|[[Direction-output]]output | `\https://admin-shell.io/aas/3/1/Direction/output`
a|Output direction
|===

{empty} +

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
|Enumeration: e|[[StateOfEvent]]StateOfEvent \<<Experimental>>
h|Explanation: a|State of an event
|Set of: |--
h|ID: | `\https://admin-shell.io/aas/3/1/StateOfEvent`

.2+h|Literal h| ID
h|Explanation

.2+e|[[StateOfEvent-on]]on | `\https://admin-shell.io/aas/3/1/StateOfEvent/on`
a|Event is on

.2+e|[[StateOfEvent-off]]off | `\https://admin-shell.io/aas/3/1/StateOfEvent/off`
a|Event is off
|===

Events sent or received by an Asset Administration Shell always comply with a general format.
Exception: events exchanged in the course of an Industry 4.0 interaction pattern.

The payload of such an event is specified below.

====
Note: the payload is not part of the information model as exchanged via the AASX package format but used in re-active Asset Administration Shells.
====

.Metamodel of Event Payload
[plantuml, 31-event-payload, svg]
....
include::partial$diagrams/31-event-payload.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[EventPayload]]EventPayload \<<Experimental>>
h|Explanation: 3+a|Defines the necessary information of an event instance sent out or received
h|Inherits from: 3+|-
h|ID: 3+| `\https://admin-shell.io/aas/3/1/EventPayload`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|[[EventPayload-source]]source 3+| `\https://admin-shell.io/aas/3/1/EventPayload/source`
a|Reference to the source event element |ModelReference<xref:EventElement[EventElement]> |1

.2+e|[[EventPayload-sourceSemanticId]]sourceSemanticId 3+| `\https://admin-shell.io/aas/3/1/EventPayload/sourceSemanticId`
a|
semanticId of the source event element, if available


====
Note: it is recommended to use an external reference.
====


|xref:spec-metamodel/referencing.adoc#Reference[Reference] |0..1

.2+e|[[EventPayload-observableReference]]observableReference 3+| `\https://admin-shell.io/aas/3/1/EventPayload/observableReference`
a|Reference to the referable, which defines the scope of the event. |ModelReference<xref:spec-metamodel/common.adoc#Referable[Referable]> |1

.2+e|[[EventPayload-observableSemanticId]]observableSemanticId 3+| `\https://admin-shell.io/aas/3/1/EventPayload/observableSemanticId`
a|
semanticId of the referable, which defines the scope of the event, if available.


====
Note: it is recommended to use an external reference.
====


|xref:spec-metamodel/referencing.adoc#Reference[Reference] |0..1

.2+e|[[EventPayload-topic]]topic 3+| `\https://admin-shell.io/aas/3/1/EventPayload/topic`
a|Information for the outer message infrastructure to schedule the event for the respective communication channel |xref:spec-metamodel/datatypes.adoc#MessageTopicType[MessageTopicType] |0..1

.2+e|[[EventPayload-subjectId]]subjectId 3+| `\https://admin-shell.io/aas/3/1/EventPayload/subjectId`
a|
Subject, who/which initiated the creation


====
Note: this is an external reference.
====


|xref:spec-metamodel/referencing.adoc#Reference[Reference] |0..1

.2+e|[[EventPayload-timestamp]]timestamp 3+| `\https://admin-shell.io/aas/3/1/EventPayload/timestamp`
a|Timestamp in UTC, when this event was triggered |xref:spec-metamodel/datatypes.adoc#DateTimeUtc[DateTimeUtc] |1

.2+e|[[EventPayload-payload]]payload 3+| `\https://admin-shell.io/aas/3/1/EventPayload/payload`
a|Event-specific payload |xref:spec-metamodel/datatypes.adoc#BlobType[BlobType] |0..1
|===

For more information on the concept of subject, see Attribute Based Access Control (ABAC) xref:bibliography.adoc#bib49[[49\]].
The assumption is that every subject has a unique identifier.

== Blob Attributes

.Metamodel of Blobs
[plantuml, 32-blob, svg]
....
include::partial$diagrams/32-blob.puml[]
....


For information on content type, see Clause xref:spec-metamodel/submodel-elements.adoc#file-attributes[File Attributes].

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Blob]]Blob
h|Explanation: 3+a|A Blob is a data element representing a file that is contained in the value attribute with its source code.
h|Inherits from: 3+|xref:DataElement[DataElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Blob`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|[[Blob-value]]value  3+| `\https://admin-shell.io/aas/3/1/Blob/value`
a|
The value of the blob instance of a blob data element


====
Note: in contrast to the file property, the file content is stored directly as value in the Blob data element.
====


|xref:spec-metamodel/datatypes.adoc#BlobType[BlobType] |0..1

.2+e|[[Blob-contentType]]contentType  3+| `\https://admin-shell.io/aas/3/1/Blob/contentType`
a|
Content type of the content of the blob.

The content type (MIME type) states which file extensions the file can have.

Valid values are content types like "application/json", "application/xls", "image/jpg".

The allowed values are defined as in RFC2046.

|xref:spec-metamodel/datatypes.adoc#ContentType[ContentType] |0..1
|===

== Capability Attributes

.Metamodel of Capabilities
[plantuml, 33-capability, svg]
....
include::partial$diagrams/33-capability.puml[]
....


====
Note: the _semanticId_ of a capability is typically an ontology, which enables reasoning on capabilities.
For information and examples on how to apply the concept of capability and how to map it to one or more skills implementing the capability, please refer to xref:bibliography.adoc#bib27[[27\]].
The mapping is done via a relationship element with the corresponding semantics.
A skill is typically a property or an operation.
In more complex cases, the mapping can also be a collection or a complete submodel.
====

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Capability]]Capability
h|Explanation: 3+a|A capability is the implementation-independent description of the potential of an asset to achieve a certain effect in the physical or virtual world.
h|Inherits from:
3+|xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Capability`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.
|===




[#data-element-and-overview-of-data-element-types]
== Data Element and Overview of Data Element Types

.Metamodel of Data Elements
[[image-34-data-element]]
[plantuml, 34-data-element, svg]
....
include::partial$diagrams/34-data-element.puml[]
....


A data element is a submodel element that is not further composed of other submodel elements.

A data element is a submodel element that has a value or a predefined number of values like range data elements.

The type of value differs for different subtypes of data elements.
Data elements include properties, file handling, and reference elements, see <<image-34-data-element>>.

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[DataElement]]DataElement \<<abstract>>
h|Explanation: 3+a|
A data element is a submodel element that is not further composed of other submodel elements.

A data element is a submodel element that has a value.
The type of value differs for different subtypes of data elements.

{aasd090}


====
Note: categories are deprecated and should no longer be used.
====



h|Inherits from: 3+|xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/DataElement`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.
|===

[[entity-attributes]]
== Entity Attributes

.Metamodel of Entities
[plantuml, 35-entity, svg]
....
include::partial$diagrams/35-entity.puml[]
....


The entity submodel element is designed to be used in submodels defining the relationship between the parts of the composite asset it is composed of (e.g. bill of material).
These parts are called entities.
Not all entities have a global asset ID.

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Entity]]Entity
h|Explanation: 3+a|
An entity is a submodel element that is used to model entities.

{aasd014}


h|Inherits from: 3+|
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Entity`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|[[Entity-statements]]statement 3+| `\https://admin-shell.io/aas/3/1/Entity/statements`
a| Statement applicable to the entity, each statement described by submodel element - typically with a qualified value |xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement] |0..*

.2+e|[[Entity-entityType]]entityType 3+| `\https://admin-shell.io/aas/3/1/Entity/entityType`
a|Describes whether the entity is a co-managed entity or a self-managed entity |xref:EntityType[EntityType]|0..1

.2+e|[[Entity-globalAssetId]]globalAssetId 3+| `\https://admin-shell.io/aas/3/1/Entity/globalAssetId`
a|Global identifier of the asset the entity is representing |xref:spec-metamodel/datatypes.adoc#Identifier[Identifier] |0..1

.2+e|[[Entity-specificAssetIds]]specificAssetId 3+| `\https://admin-shell.io/aas/3/1/Entity/specificAssetIds`
a|Reference to a specific asset ID representing a supplementary identifier of the asset represented by the Asset Administration Shell |xref:spec-metamodel/core.adoc#SpecificAssetId[SpecificAssetId] |0..*
|===

{empty} +

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
|Enumeration: e|[[EntityType]]EntityType
h|Explanation: a|Enumeration for denoting whether an entity is a self-managed entity or a co-managed entity
|Set of: |--
h|ID: | `\https://admin-shell.io/aas/3/1/EntityType`

.2+h|Literal h| ID
h|Explanation

.2+e|[[EntityType-CoManagedEntity]]CoManagedEntity | `\https://admin-shell.io/aas/3/1/EntityType/CoManagedEntity`
a|
There is no separate Asset Administration Shell for co-managed entities.
Co-managed entities need to be part of a self-managed entity.

.2+e|[[EntityType-SelfManagedEntity]]SelfManagedEntity | `\https://admin-shell.io/aas/3/1/EntityType/SelfManagedEntity`
a|
Self-managed entities have their own Asset Administration Shell but can be part of another composite self-managed entity.

The asset represented by an Asset Administration Shell is a self-managed entity per definition.

|===

[#event-element-attributes]
== Event Element Attributes

.Metamodel of Event Elements
[plantuml, 36-event-element, svg]
....
include::partial$diagrams/36-event-element.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[EventElement]]EventElement \<<abstract>> \<<Experimental>>
h|Explanation: 3+a|An event element
h|Inherits from: 3+|xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/EventElement`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.
|===

[#file-attributes]
== File Attributes

.Metamodel of File Submodel Element
[plantuml, 37-file, svg]
....
include::partial$diagrams/37-file.puml[]
....


A media type (also MIME type and content type) is a two-part identifier for file formats and format contents transmitted via the Internet.
The Internet Assigned Numbers Authority (IANA) is the official authority for the standardization and publication of these classifications.

====
Note: for information on handling supplementary external files in exchanging Asset Administration Shells in AASX package format see also Part 5 of the series link:https://industrialdigitaltwin.org/en/content-hub/aasspecifications["Specification of the Asset Administration Shell"].
An absolute path is used in case the file exists independently of the Asset Administration Shell.
A relative path, relative to the package root, should be used if the file is part of a serialized package of the Asset Administration Shell.
====

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[File]]File
h|Explanation:
3+a|A file is a data element that represents an address to a file (a locator).
The value is a URI that can represent an absolute or relative path.
h|Inherits from: 3+|xref:DataElement[DataElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/File`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|value 3+| `\https://admin-shell.io/aas/3/1/File/value`
a|
Path and name of the file (with file extension)

The path can be absolute or relative.

|xref:spec-metamodel/datatypes.adoc#PathType[PathType] |0..1

.2+e|contentType 3+| `\https://admin-shell.io/aas/3/1/File/contentType`
a|Content type of the content of the file |xref:spec-metamodel/datatypes.adoc#ContentType[ContentType] |0..1
|===

== Multi Language Property Attributes

.Metamodel of Multi Language Properties
[plantuml, 38-multi-language-property, svg]
....
include::partial$diagrams/38-multi-language-property.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[MultiLanguageProperty]]MultiLanguageProperty
h|Explanation: 3+a|
A property is a data element that has a multi-language value.

{aasd012}


h|Inherits from: 3+|xref:DataElement[DataElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/MultiLanguageProperty`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|value 3+| `\https://admin-shell.io/aas/3/1/MultiLanguageProperty/value`
a|The value of the property instance |xref:spec-metamodel/datatypes.adoc#MultiLanguageTextType[MultiLanguageTextType] |0..1

.2+e|valueId 3+| `\https://admin-shell.io/aas/3/1/MultiLanguageProperty/valueId`
a|
Reference to the global unique ID of a coded value.



|xref:spec-metamodel/referencing.adoc#Reference[Reference] |0..1
|===

== Operation Attributes

.Metamodel of Operations
[plantuml, 39-operation, svg]
....
include::partial$diagrams/39-operation.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Operation]]Operation
h|Explanation: 3+a|
An operation is a submodel element with input and output variables.

{aasd134}


h|Inherits from: 3+|xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Operation`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|inputVariable 3+| `\https://admin-shell.io/aas/3/1/Operation/inputVariables`
a|Input parameter of the operation |xref:OperationVariable[OperationVariable] |0..*

.2+e|outputVariable 3+| `\https://admin-shell.io/aas/3/1/Operation/outputVariables`
a|Output parameter of the operation |xref:OperationVariable[OperationVariable] |0..*

.2+e|inoutputVariable 3+| `\https://admin-shell.io/aas/3/1/Operation/inoutputVariables`
a|Parameter that is input and output of the operation |xref:OperationVariable[OperationVariable] |0..*
|===

{empty} +

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[OperationVariable]]OperationVariable
h|Explanation: 3+a|The value of an operation variable is a submodel element that is used as input and/or output variable of an operation.
h|Inherits from: 3+|--
h|ID: 3+| `\https://admin-shell.io/aas/3/1/OperationVariable`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|value 3+| `\https://admin-shell.io/aas/3/1/OperationVariable/value`
a|Describes an argument or result of an operation via a submodel element |xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement] |1
|===

====
Note 1: an operation can  be invoked via an API call. For further explanation see Part 2 (IDTA-01002).
====

====
Note 2: OperationVariable is introduced as separate class to enable future extensions, e.g. for adding a default value or cardinality (option/mandatory).
====

====
Note 3: even if the submodel element as the value of an input and an output variable have the same idShort, this does not mean that they are identical or mapped to the same variable since OperationVariables are no referables.
The same applies to two input variables or an input variable and an inoutputVariable a.s.o.
====

[#property-attributes]
== Property Attributes

.Metamodel of Properties
[plantuml, 40-property, svg]
....
include::partial$diagrams/40-property.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Property]]Property
h|Explanation: 3+a|
A property is a data element that has a single value.

{aasd007}


h|Inherits from: 3+|xref:DataElement[DataElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Property`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|valueType 3+| `\https://admin-shell.io/aas/3/1/Property/valueType`
a|Data type of the value attribute |xref:spec-metamodel/datatypes.adoc#DataTypeDefXsd[DataTypeDefXsd] |1

.2+e|value 3+| `\https://admin-shell.io/aas/3/1/Property/value`
a|The value of the property instance |xref:spec-metamodel/datatypes.adoc#ValueDataType[ValueDataType] |0..1

.2+e|valueId 3+| `\https://admin-shell.io/aas/3/1/Property/valueId`
a| Reference to the global unique ID of a coded value


====
Note: it is recommended to use an external reference, compare to xref:spec-metamodel/common.adoc#HasSemantics[HasSemantics/semanticId]
====


|xref:spec-metamodel/referencing.adoc#Reference[Reference] |0..1
|===

[[range-attributes]]
== Range Attributes

.Metamodel of Ranges
[plantuml, 41-range, svg]
....
include::partial$diagrams/41-range.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[Range]]Range \<<Experimental>>
h|Explanation: 3+a|A range data element is a data element that defines a range with min and max.
h|Inherits from: 3+|xref:DataElement[DataElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/Range`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|valueType 3+| `\https://admin-shell.io/aas/3/1/Range/valueType`
a|Data type of the min und max attributes |xref:spec-metamodel/datatypes.adoc#DataTypeDefXsd[DataTypeDefXsd] |1

.2+e|min 3+| `\https://admin-shell.io/aas/3/1/Range/min`
a|
The minimum value of the range

If the min value is missing, the value is assumed to be negative infinite.

|xref:spec-metamodel/datatypes.adoc#ValueDataType[ValueDataType] |0..1

.2+e|max 3+| `\https://admin-shell.io/aas/3/1/Range/max`
a|
The maximum value of the range

If the max value is missing, the value is assumed to be positive infinite.

|xref:spec-metamodel/datatypes.adoc#ValueDataType[ValueDataType] |0..1
|===

== Reference Element Attributes

.Metamodel of Reference Elements
[plantuml, 42-reference-element, svg]
....
include::partial$diagrams/42-reference-element.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[ReferenceElement]]ReferenceElement
h|Explanation: 3+a|A reference element is a data element that defines a logical reference to another element within the same or another Asset Administration Shell or a reference to an external object or entity.
h|Inherits from: 3+|xref:DataElement[DataElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/ReferenceElement`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|value  3+| `\https://admin-shell.io/aas/3/1/ReferenceElement/value`
a|External reference to an external object or entity or a logical reference to another element within the same or another Asset Administration Shell (i.e. a model reference to a _Referable_) |xref:spec-metamodel/referencing.adoc#Reference[Reference] |0..1
|===

For more information on references, see Clause xref:spec-metamodel/referencing.adoc[].

[#relationship-element-attributes]
== Relationship Element Attributes

The semantics of the relationship is defined via the _semanticId_ of the _RelationshipElement_.
If this semantic definition requires additional information not contained in the _first_ or _second_ object referenced via the relationship, the submodel element type xref:spec-metamodel/submodel-elements.adoc#annotated-relationship-element-attributes[AnnotatedRelationshipElement] shall be used instead.

.Metamodel of Relationship Elements
[plantuml, 43-relationship-element, svg]
....
include::partial$diagrams/43-relationship-element.puml[]
....


[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[RelationshipElement]]RelationshipElement
h|Explanation: 3+a|A relationship element is used to define a relationship between two elements being either referable (model reference) or external (external reference).
h|Inherits from: 3+|xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement]
h|ID: 3+| `\https://admin-shell.io/aas/3/1/RelationshipElement`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|first 3+| `\https://admin-shell.io/aas/3/1/RelationshipElement/first`
a|Reference to the first element in the relationship taking the role of the subject |xref:spec-metamodel/referencing.adoc#Reference[Reference] | 0..1

.2+e|second 3+| `\https://admin-shell.io/aas/3/1/RelationshipElement/second`
a|Reference to the second element in the relationship taking the role of the object |xref:spec-metamodel/referencing.adoc#Reference[Reference] | 0..1
|===

[#submodel-element-collection-attributes]
== Submodel Element Collection Attributes

.Metamodel of Submodel Element Collections
[plantuml, 44-submodel-element-collection, svg]
....
include::partial$diagrams/44-submodel-element-collection.puml[]
....


Submodel Element Collections are used for complex elements with a typically fixed set of properties with unique names.
This set of properties is typically predefined by the semantic definition (referenced via xref:spec-metamodel/common.adoc#HasSemantics[semanticId]) of the submodel element collection.
Each property within the collection itself should have clearly defined semantics.

====
Note: the different elements of a submodel element collection do not have to have different xref:spec-metamodel/common.adoc#HasSemantics[semanticIds].
However, in these cases the usage of a xref:spec-metamodel/submodel-elements.adoc#SubmodelElementList[SubmodelElementList] should be considered.
====

Example: a single document has a predefined set of properties like title, version, author, etc.
They logically belong to a document.
So a single document is represented by a _SubmodelElementCollection_.
An asset usually has many different documents available like operating instructions, safety instructions, etc.
The set of all documents is represented by a xref:spec-metamodel/submodel-elements.adoc#submodel-element-list-attributes[SubmodelElementList].
In this case, we have a xref:spec-metamodel/submodel-elements.adoc#submodel-element-list-attributes[SubmodelElementList] of xref:spec-metamodel/submodel-elements.adoc#submodel-element-collection-attributes[SubmodelElementCollection]s.

====
Note: the elements within a submodel element collection are not ordered.
Every element has a unique ID (its "idShort").
However, it is recommended to adhere to the order defined in the submodel template.
====

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[SubmodelElementCollection]]SubmodelElementCollection
h|Explanation: 3+a|A submodel element collection is a kind of struct, i.e. a logical encapsulation of multiple named values.
h|Inherits from: 3+|
h|ID: 3+| `\https://admin-shell.io/aas/3/1/SubmodelElementCollection`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|value 3+| `\https://admin-shell.io/aas/3/1/SubmodelElementCollection/values`
|Submodel element contained in the collection |xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement] |0..*
|===

[#submodel-element-list-attributes]
== Submodel Element List Attributes

.Metamodel of Submodel Element Lists
[plantuml, 45-submodel-element-list, svg]
....
include::partial$diagrams/45-submodel-element-list.puml[]
....


Submodel element lists are used for sets (i.e. unordered collections without duplicates), ordered lists (i.e. ordered collections that may contain duplicates), bags (i.e. unordered collections that may contain duplicates), and ordered sets (i.e. ordered collections without duplicates).


Submodel element lists are also used to create multidimensional arrays.
A two-dimensional array listxref:bibliography.adoc#bib3[[3\]]xref:bibliography.adoc#bib5[[5\]] with _Property_ values would be realized like follows: the first submodel element list would contain three xref:spec-metamodel/submodel-elements.adoc#submodel-element-list-attributes[SubmodelElementList] elements.
Each of these three xref:spec-metamodel/submodel-elements.adoc#submodel-element-list-attributes[SubmodelElementList] would contain 5 single xref:spec-metamodel/submodel-elements.adoc#property-attributes[Property] elements.
The xref:spec-metamodel/common.adoc#HasSemantics[semanticId] of the contained properties would be the same for all lists in the first list, i.e. xref:spec-metamodel/submodel-elements.adoc#submodel-element-list-attributes[semanticIdListElement] would be identical for all three lists contained in the first list.
The _semanticId_ of the three contained lists would differ depending on the dimension it represents.
In case of complex values in the array, a xref:spec-metamodel/submodel-elements.adoc#submodel-element-collection-attributes[SubmodelElementCollection]  would be used as values in the leaf lists.

Similarly, a table with three columns can be represented.
In this case a _SubmodelElementCollection_ with three xref:spec-metamodel/submodel-elements.adoc#SubmodelElementList[SubmodelElementLists]  would be contained and the xref:spec-metamodel/common.adoc#HasSemantics[semanticId] as well as the xref:spec-metamodel/submodel-elements.adoc#SubmodelElementList[semanticIdListElement] for the three columns would differ.

Matching strategies for semantic IDs are explained in Clause xref:annex/general.adoc#matching-strategies-for-semantic-identifiers[Matching Strategies for Semantic Identifiers].

[.table-with-appendix-table]
[cols="25%,40%,25%,10%"]
|===
h|Class: 3+e|[[SubmodelElementList]]SubmodelElementList
h|Explanation: 3+a|
A submodel element list is an ordered list of submodel elements.


====
Note: the list is ordered although the ordering might not be relevant (see attribute "orderRelevant".)
====


The numbering starts with Zero (0).

{aasd107}

{aasd114}

{aasd115}

{aasd108}

{aasd109}


h|Inherits from: 3+|
h|ID: 3+| `\https://admin-shell.io/aas/3/1/SubmodelElementList`

.2+h|Attribute 3+h| ID
h|Explanation h|Type h|Card.

.2+e|orderRelevant 3+| `\https://admin-shell.io/aas/3/1/SubmodelElementList/orderRelevant`
a|
Defines whether order in list is relevant.
If _orderRelevant_ = false, the list represents a set or a bag.

Default: True

|boolean |0..1

.2+e|value 3+| `\https://admin-shell.io/aas/3/1/SubmodelElementList/values`
a|Submodel element contained in the list |xref:spec-metamodel/core.adoc#SubmodelElement[SubmodelElement] |0..*

.2+e|semanticIdListElement 3+| `\https://admin-shell.io/aas/3/1/SubmodelElementList/semanticIdListElement`
a|
Semantic ID which the submodel elements contained in the list match





|xref:spec-metamodel/referencing.adoc#Reference[Reference] |0..1

.2+e|typeValueListElement  3+| `\https://admin-shell.io/aas/3/1/SubmodelElementList/typeValueListElement/typeValueListElement`
a|The submodel element type of the submodel elements contained in the list |xref:spec-metamodel/referencing.adoc#AasSubmodelElements[AasSubmodelElements]|1

.2+e|valueTypeListElement 3+| `\https://admin-shell.io/aas/3/1/SubmodelElementList/valueTypeListElement`
a|The value type of the submodel element contained in the list |xref:spec-metamodel/datatypes.adoc#DataTypeDefXsd[DataTypeDefXsd]|0..1
|===