////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////

=== Format "Path" (idShortPath Serialization) in JSON

To get only the idShortPaths of a submodel element hierarchy, the serialization format is specified in terms of an idShortPath notation to be returned in an JSON array.
The notation differs depending on whether a SubmodelElementCollection or a SubmodelElementList is present.
In the first case, the submodel element's idShort is separated by "." (dot) from top level down to child level.
In the second case, square brackets with an index "[<Index>]" are appended after the idShort of the containing SubmodelElementList.
In any case, the first item of any idShortPath is the idShort of the requested element.

[.underline]#Grammar:#

[listing]
....
<idShortPath> ::= <idShort> {["." <idShort> | "["<Index>"]" ]}* 

<Index> ::= <Zero> | <PositiveNumber>

<PositiveNumber>  ::= <NonZeroDigit>{<Digit>}*
<Digit> ::= <Zero> | <NonZeroDigit>
<Zero>  ::= "0"
<NonZeroDigit>  ::= "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
....

In the following example, where a request for idShortPaths targets a  _MySubmodelElementCollection_ with SerializationModifier level = deep, the list of idShortPaths is returned as follows:

====
EXAMPLE Submodel


Submodel: MySubmodel

* Property: MyTopLevelProperty
* SMC: MySubmodelElementCollection
** Property: MySubProperty1
** Property: MySubProperty2
** SMC: MySubSubmodelElementCollection
*** Property: MySubSubProperty1
*** Property: MySubSubProperty2
** SML: MySubSubmodelElementList1
*** Property: "MySubTestValue1"
*** Property: "MySubTestValue2"
** SML: MySubSubmodelElementList2
*** SML
**** Property: "MySubTestValue3"
====

idShortPaths for SMC MySubmodelElementCollection within the Submodel above:

[source,json,linenums]
----
[
  "MySubmodelElementCollection",
  "MySubmodelElementCollection.MySubProperty1",
  "MySubmodelElementCollection.MySubProperty2",
  "MySubmodelElementCollection.MySubmodelElementCollection",
  "MySubmodelElementCollection.MySubmodelElementCollection.MySubProperty1",
  "MySubmodelElementCollection.MySubmodelElementCollection.MySubProperty2",
  "MySubmodelElementCollection.MySubSubmodelElementList1",
  "MySubmodelElementCollection.MySubSubmodelElementList1[0]",
  "MySubmodelElementCollection.MySubSubmodelElementList1[1]",
  "MySubmodelElementCollection.MySubSubmodelElementList2",
  "MySubmodelElementCollection.MySubSubmodelElementList2[0]",
  "MySubmodelElementCollection.MySubSubmodelElementList2[0][0]"
]
----

====
Note: There is no idShortPath for Identifiables because idShort is optional for Identifiables.
====
