////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////



=== Format "Value" (Value-Only Serialization) in JSON


==== Overview of Value-Only Serialization Attributes
In many cases, applications using data from Asset Administration Shells already know the Submodel regarding its structure, attributes, and semantics. Consequently, there is not always a need to receive the entire model information, which can be requested separately via _Content_ modifier set to _Metadata_, in each request since it is constant most of the time. Instead, applications are most likely only interested in the values of the modelled data. Furthermore, having limited processing power or limited bandwidth, one use case of this format is to transfer data as efficiently as possible. Semantics and data might be split into two separate architecture building blocks. For example, a database would suit the needs for querying semantics, while a device would only provide the data at runtime. Two separate requests make it possible to build up a user interface (UI) and show new upcoming values highly efficiently.

Values are only available for

* All subtypes of abstract type _DataElement_,
* SubmodelElementList and SubmodelElementCollection resp. for their included SubmodelElements,
* ReferenceElement,
* RelationshipElement + AnnotatedRelationshipElement,
* Entity,
* BasicEventElement,
* Submodel.

Capabilities are excluded from the serialization scope since only data containing elements are in the focus. They are consequently omitted in the serialization.


The Value-Only Format does not contain Metadata attributes (see xref:IDTA-01001_Mappings.adoc#format-metadata-metadata-serialization[Metadata Attributes]) but only the value-related data.

[[table-value-data-attributes]]
.Value-Only Attributes
[%autowidth, width="100%", cols="48%,52%",options="header",]
|===
|*Class Name* |*Fields for Value-Only representationfootnote:[ attribute in parenthesis - like e.g. (value) - means that the attribute name is not displayed, only its Value-Only serialization. 
For the other attributes the attribute itself will be part of the serialization]*
2+|*Identifiables*
|AssetAdministrationShell a|assetInformation, submodels
|Submodel a| (submodelElements)

|*SubmodelElements* a| 

|SubmodelElementCollection a| (value) 

|SubmodelElementList a| (value) 

if defined: type equal to SubmodelElementList/valueTypeListElement

|Entity |statements, globalAssetId, specificAssetId
|BasicEventElement a|observed
|Capability a| -
|Operation a| -

|RelationshipElement a|first, second

|AnnotatedRelationshipElement a|first, second, annotations

2+|*DataElements*
|Property a| (value)

type equal to Property/valueType

|MultilanguageProperty a| (value)

|Range a|min, max

type equal to Range/valueType

|ReferenceElement a|(value)

|Blob a|value, contentType
|File a|value, contentType

2+|*Non-Referables*
|OperationVariable a| (value)

|===

The following restrictions hold:

* Qualifiers are ignored in Value-Only serialization. This also holds for qualifiers of kind "ValueQualifier"
* valueId (as used in Property and MultiLanguageProperty) is ignored in Value-Only serialization

====
There is no Value-Only serialization for an Operation. However, a Value-Only serialization is useful for its arguments when executing the operation (see Value-Only serialization of "OperationVariable")
====

==== Rules for Value-Only Serialization

The following rules shall be adhered to when serializing a submodel with the format _Value_footnote:[see SerializationModifier in Part 2 of the Specification of the Asset Administration Shell]:

* A submodel is serialized as an unnamed JSON object.
* A submodel element is considered a leaf submodel element if it does not contain other submodel elements. A leaf submodel element follows the rules for the different submodel elements considered in the serialization, as described below. If it is not a leaf element, the serialization rules must be transitively followed until the value is a leaf submodel element.
* For each submodel element:

** _Property_ is serialized as $\{Property/idShort}: $\{Property/value} where $\{Property/value} is the JSON serialization of the respective property’s value in accordance with the data type to value mapping (see table after this section).
** _MultiLanguageProperty_ is serialized as named JSON object with $\{MultiLanguageProperty/idShort} as the name of the containing JSON property. The JSON object contains an array of JSON objects for each language of the _MultiLanguageProperty_ with the language as name and the corresponding localized string as value of the respective JSON property. The language name is defined as two chars according to ISO 639-1.
** _Range_ is serialized as named JSON object with $\{Range/idShort} as the name of the containing JSON property. The JSON object contains two JSON properties. The first is named “min”. The second is named “max”. Their corresponding values are $\{Range/min} and $\{Range/max}.
** _File_ and _Blob_ are serialized as named JSON objects with $\{File/idShort} or $\{Blob/idShort}as the name of the containing JSON property. The JSON object contains two JSON properties. The first refers to the content type named $\{File/contentType} resp. $\{Blob/contentType}. The latter refers to the value named “value” $\{File/value} resp. $\{Blob/value}. The resulting ValueOnly object is indistinguishable whether it contains File or Blob attributes. Therefore, the receiver needs to take the type of the target resource into account. Since the receiver knows in advance if a File or a Blob SubmodelElement shall be manipulated, it can parse the transferred ValueOnly object accordingly as a File or Blob object.
** _SubmodelElementCollection_ is serialized as named JSON object with $\{SubmodelElementCollection/idShort} as the name of the containing JSON property. The elements contained within the struct are serialized according to their respective type with $\{SubmodelElement/idShort} as the name of the containing JSON property.
** _SubmodelElementList_ is serialized as a named JSON array with $\{SubmodelElementList/idShort} as the name of the containing JSON property. The elements in the JSON array are the ValueOnly serializations of the elements contained in the SubmodelElementList while preserving the order, i.e. index n in the JSON array is the ValueOnly serialization of the element at index n of the SubmodelElementList.
** _ReferenceElement_ is serialized as $\{ReferenceElement/idShort}: $\{ReferenceElement/value} where $\{ReferenceElement/value} is the serialization of the _Reference_ class.
** _RelationshipElement_ is serialized as named JSON object with $\{RelationshipElement/idShort} as the name of the containing JSON property. The JSON object contains two JSON properties. The first is named “first”. The second is named “second”. Their corresponding values are $\{RelationshipElement/first} resp. $\{Relationship/second}. The values are serialized according to the serialization of a _ReferenceElement_ (see above).
** _AnnotatedRelationshipElement_ is serialized according to the serialization of a _ReleationshipElement_ (see above). Additionally, a third named JSON object is introduced with “annotations” as the name of the containing JSON property. The value is $\{AnnotatedRelationshipElement/annotations}. The values of the array items are serialized depending on the type of the annotation data element.
** _Entity_ is serialized as named JSON object with $\{Entity/idShort} as the name of the containing JSON property. The JSON object contains three JSON properties. The first is named “statements” $\{Entity/statements} and contains an array of the serialized submodel elements according to their respective serialization mentioned in this clause. The second is named either “globalAssetId” or “specificAssetId” and contains either a _Reference_ (see above) or a _SpecificAssetId_. The third property is named “entityType” and contains a string representation of $\{Entity/entityType}.
** _BasicEventElement_ is serialized as named JSON object with $\{BasicEventElement/idShort} as the name of the containing JSON property. The JSON object contains one JSON property named “observed” with the corresponding value of $\{BasicEventElement/observed} as the standard serialization of the _Reference_ class.
** _SpecificAssetId_ is serialized as named JSON object with three JSON properties named as the attributes of _SpecificAssetId._

* Submodel elements defined in the submodel other than the ones mentioned above are not subject to serialization of that SerializationModifier.

==== Data type to value mapping

The serialization of submodel element values is described in the following table. The left column “Data Type” shows the data types which can be used for submodel element values. The data types are defined according to the W3C XML Schema (https://www.w3.org/TR/xmlschema-2/#built-in-datatypes and https://www.w3.org/TR/xmlschema-2/#built-in-derived). “Value Range” further explains the possible range of data values for this data type. The right column comprises related examples of the serialization of submodel element values.

[[data-types-value-only]]
.Mapping of Data Types in ValueOnly-Serializationfootnote:[cf. https://eclipse-esmf.github.io/samm-specification/2.0.0/datatypes.html]
[%autowidth, width="100%", cols="15%,15%,9%,30%,31%",options="header",]
|===
| |*Data Type* |*JSON Type* |*Value Range* |*Sample Values*
|Core Types |xs:string |string |Character string |"Hello world", "Καλημέρα κόσμε", "コンニチハ"
| |xs:boolean |boolean |true, false |true, false
| |xs:decimal |number |Arbitrary-precision decimal numbers |-1.23, 126789672374892739424.543233, 100000.00, 210
| |xs:integer |number |Arbitrary-size integer numbers |-1, 0, 126789675432332938792837429837429837429, 100000
|IEEE-floating-point numbers |xs:double |number |64-bit floating point numbers |-1.0, -0.0, 0.0, 234.567e8, 234.567e+8, 234.567e-8
| |xs:float |number |32-bit floating point numbers |-1.0, -0.0, 0.0, 234.567e8, 234.567e+8, 234.567e-8
|Time and data |xs:date |string |Dates (yyyy-mm-dd) with or without time zone |"2000-01-01","2000-01-01Z", "2000-01-01+12:05"
| |xs:time |string |Times (hh:mm:ss.sss…​) with or without time zone |"14:23:00", "14:23:00.527634Z", "14:23:00+03:00"
| |xs:dateTime |string |Date and time with or without time zone |"2000-01-01T14:23:00", "2000-01-01T14:23:00.66372+14:00"
| |xs:dateTimeStamp |string |Date and time with required time zone |"2000-01-01T14:23:00.66372+14:00"
|Recurring and partial dates |xs:gYear |string |Gregorian calendar year |"2000", "2000+03:00"
| |xs:gMonth |string |Gregorian calendar month |"--04", "--04+03:00"
| |xs:gDay |string |Gregorian calendar day of the month |"---04", "---04+03:00"
| |xs:gYearMonth |string |Gregorian calendar year and month |"2000-01", "2000-01+03:00"
| |xs:gMonthDay |string |Gregorian calendar month and day |"--01-01", "--01-01+03:00"
| |xs:duration |string |Duration of time |"P30D", "-P1Y2M3DT1H", "PT1H5M0S"
| |xs:yearMonthDuration |string |Duration of time (months and years only) |"P10M", 'P5Y2M"
| |xs:dayTimeDuration |string |Duration of time (days, hours, minutes, seconds only) |"P30D", 'P1DT5H", 'PT1H5M0S"
|Limited-range integer numbers |xs:byte |number |-128…+127 (8 bit) |-1, 0, 127
| |xs:short |number |-32768…+32767 (16 bit) |-1, 0, 32767
| |xs:int |number |2147483648…+2147483647 (32 bit) |-1, 0, 2147483647
| |xs:long |number |-9223372036854775808…+9223372036854775807 (64 bit) |-1, 0, 9223372036854775807
| |xs:unsignedByte |number |0…255 (8 bit) |0, 1, 255
| |xs:unsignedShort |number |0…65535 (16 bit) |0, 1, 65535
| |xs:unsignedInt |number |0…4294967295 (32 bit) |0, 1, 4294967295
| |xs:unsignedLong |number |0…18446744073709551615 (64 bit) |0, 1, 18446744073709551615
| |xs:positiveInteger |number |Integer numbers >0 |1, 7345683746578364857368475638745
| |xs:nonNegativeInteger |number |Integer numbers ≥0 |0, 1, 7345683746578364857368475638745
| |xs:negativeInteger |number |Integer numbers <0 |-1, -23487263847628376482736487263847
| |xs:nonPositiveInteger |number |Integer numbers ≤0 |-1, 0, -93845837498573987498798987394
|Encoded binary data |xs:hexBinary |string |Hex-encoded binary data |"6b756d6f77617368657265"
| |xs:base64Binary |string |base64-encoded binary data |"a3Vtb3dhc2hlcmU="
|Miscellaneous types |xs:anyURI |string |Absolute or relative URIs and IRIs |"http://customer.com/demo/aas/1/1/1234859590", "urn:example:company:1.0.0"
| |rdf:langString |string |Strings with language tags a|
"'Hello'@en", "'Hallo'@de"


====
Note: the examples are written in RDF/Turtle syntax, and only "Hello" and "Hallo" are the actual values.
====


|===

The following types defined by the XSD and RDF specifications are explicitly omitted for serialization - they are not element of _DataTypeDefXsd_ or _DataTypeDefRdf_:

xs:language, xs:normalizedString, xs:token, xs:NMTOKEN, xs:Name, xs:NCName, xs:QName, xs:ENTITY, xs:ID, xs:IDREF, xs:NOTATION, xs:IDREFS, xs:ENTITIES, xs:NMTOKENS, rdf:HTML and rdf:XMLLiteral.


====
Note 1: due to the limits in the representation of numbers in JSON, the maximum integer number that can be used without losing precision is 2^53^-1 (defined as Number.MAX_SAFE_INTEGER). Even if the used data type would allow higher or lower values, they cannot be used if they cannot be represented in JSON. Affected data types are unbounded numeric types xs:decimal, xs:integer, xs:positiveInteger, xs:nonNegativeInteger, xs:negativeInteger, xs:nonPositiveInteger and the bounded type xs:unsignedLong. Other numeric types are not affected. footnote:[cf. https://eclipse-esmf.github.io/samm-specification/2.0.0/payloads.html (with adjustments for +/-INF, NaN, and language-typed literal support)]
====



====
Note 2: the ValueOnly-serialization uses JSON native data types, AAS in general uses XML Schema Built-in Datatypes for Simple Data Types and ValueDataType. In case of booleans, JSON accepts only literals true and false, whereas xs:boolean also accepts 1 and 0, respectively. In case of double, JSON number is used in ValueOnly, but JSON number does not support INF/-INF (positive Infinity/negative), which is supported by xs:double. Furthermore, NaN (Not a Number) is also not supported. 
====

(See https://datatracker.ietf.org/doc/html/rfc8259#section-6 )


====
Note 3: language-tagged strings (rdf:langString) containing single quotes (‘) or double quotes (“) are not supported.
====

====
Note 4: Roundtrip conversion from "Normal" to "ValueOnly" format may not result in the original payload because "Normal" is using string whereas "ValueOnly" is using the JSON type closest to the xsd datatype (see table [data-types-value-only]).
====

==== Example Value-Only serialization for a Submodel

The following example shows the JSON Value-Only serialization for a Submodel with name "Example" and two direct SubmodelElements "ProductClassifications" and "MaxRotationSpeed". "ProductClassifications" is represented by a SubmodelElementList with SubmodelElementCollections as its elements. Each of the SubmodelCollections has two mandatory elements "ProductClassificationSystem" and "ProductClassId" and one optional element "ProductClassificationVersion". All of these elements have data type "xs:string". "MaxRotationSpeed" is a property with data type "xs:int".

[source,json,linenums]
----
{ "ProductClassifications": 
   [
    {
	"ProductClassificationSystem": "ECLASS",
	"ProductClassId": "27-01-88-77",
	"ProductClassificationVersion: "9.0"
    },
    {
	"ProductClassificationSystem": "IEC CDD",
	"ProductClassId": "0112/2///61987#ABA827#003",
    }
   ],
  "MaxRotationSpeed": 5000
}
----

The JSON Value-Only serialization for the element "ProductClassifications", a SubmodelElementList, within the submodel above looks like this:

[source,json,linenums]
----
   [
    {
	"ProductClassificationSystem": "ECLASS",
	"ProductClassId": "27-01-88-77",
	"ProductClassificationVersion: "9.0"
    },
    {
	"ProductClassificationSystem": "IEC CDD",
	"ProductClassId": "0112/2///61987#ABA827#003",
    }
   ]
----

The JSON Value-Only serialization for the  first element, a SubmodelElementCollection, within the "ProductClassifications" list above looks like this:

[source,json,linenums]
----
{
	"ProductClassificationSystem": "ECLASS",
	"ProductClassId": "27-01-88-77",
	"ProductClassificationVersion: "9.0"
}
----

The JSON Value-Only serialization for the Property "MaxRotationSpeed" of the submodel above looks like this:
[source,json,linenums]
----
5000
----




The Format "Normal" in comparison to this Value-Only serialization of the property "MaxRotationSpeed" would look like this:

[source,json,linenums]
----
{
  "idShort": "MaxRotationSpeed",
  "semanticId": {
    "type": "ExternalReference",
    "keys": [
      {
        "type": "GlobalReference",
        "value": "0173-1#02-BAA120#008"
      }
    ]
  },
  "modelType": "Property",
  "valueType": "xs:int",
  "value": "5000"
}
----

==== Examples Value-Only serialization for all submodel element types 

In the following examples for Value-Only serializations for all submodel element types are given.


For a single _Property_ named "MaxRotationSpeed", the value-Only payload is minimized to the following (assuming its value is 5000):
[source,json,linenums]
----
  5000
----


For a _SubmodelElementCollection_ named "ProductClassification" or being part of a list "ProductionClassifications", the Value-Only payload is minimized to the following,
i.e. the name of the SubmodelElementCollection or its index in the list is not part of the Value-Only serialization:

[source,json,linenums]
----
{
	"ProductClassificationSystem": "ECLASS",
	"ProductClassId": "27-01-88-77",
	"ProductClassificationVersion: "9.0"
}
----


For a _SubmodelElementList_ named "Authors" with string Properties as its value, the Value-Only payload is minimized to the following (values within a SubmodelElementList do not have idShort values)footnote:[The Value-Only serialization of the product classification example can be seen above]:

[source,json,linenums]
----
[
    "Martha",
    "Jonathan",
    "Clark"
]
----



For a _MultiLanguageProperty_ the Value-Only payload is minimized to the following:
[source,json,linenums]
----
[
    {"de": "Das ist ein deutscher Bezeichner"},
    {"en": "That's an English label"}
]

----





For a _Range_ named “TorqueRange”, the Value-Only payload  is minimized to the following:

[source,json,linenums]
----
{
    "min": 3,
    "max": 15
}
----

For a _ReferenceElement_ named “MaxRotationSpeedReference”, the Value-Only payload  is minimized to the following:


[source,json,linenums]
----
{
    "type": "ExternalReference",
    "keys": [
      {
        "type": "GlobalReference",
        "value": "0173-1#02-BAA120#008"
      }
    ]
}
----

For a _File_ named “Document”, the Value-Only payload is minimized to the following:

[source,json,linenums]
----
{
    "contentType": "application/pdf",
    "value": "SafetyInstructions.pdf"
}
----


For a _Blob_ named “Library”, there are two possibilities for the Value-Only payload. In case the Blob value - that can be very large - 
shall not be part of the payload the payload is minimized to the followingfootnote:[ 
for the API a special JSON query parameter, the SerializationModifier _Extent_, is set to *_WithoutBLOBValue_* for this case]

[source,json,linenums]
----
{
    "contentType": "application/octet-stream"
}
----

In the second case the Blob value is part of the payload.footnote:[in this case the JSON query parameter SerializationModifier Extent is set to *_WithBlobValue_*], 
there is an additional attribute containing the base64-encoded value:

[source,json,linenums]
----
{
    "contentType": "application/octet-stream",
    "value": "VGhpcyBpcyBteSBibG9i"
}
----

For a _RelationshipElement_ named “CurrentFlowsFrom”, the Value-Only payload is minimized to the following:


[source,json,linenums]
----
{
    "first": {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://customer.com/demo/aas/1/1/1234859590"
        },
        {
          "type": "Property",
          "value": "PlusPole"
        }
      ]
    },
    "second": {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://customer.com/demo/aas/1/0/1234859123490"
        },
        {
          "type": "Property",
          "value": "MinusPole"
        }
      ]
    }
}
----

For an _AnnotatedRelationshipElement_ named “CurrentFlowFrom”, with an annotated _Property_-DataElement “AppliedRule”, the Value-Only-payload  is minimized to the following:



[source,json,linenums]
----
{
    "first": {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://customer.com/demo/aas/1/1/1234859590"
        },
        {
          "type": "Property",
          "value": "PlusPole"
        }
      ]
    },
    "second": {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://customer.com/demo/aas/1/0/1234859123490"
        },
        {
          "type": "Property",
          "value": "MinusPole"
        }
      ]
    },
    "annotations": [
      {
        "AppliedRule": "TechnicalCurrentFlowDirection"
      }
    ]
}
----

For an _Entity_ named “MySubAssetEntity”, the Value-Only-payload is minimized to the following:


[source,json,linenums]
----
{
    "statements": {
      "MaxRotationSpeed": 5000
    },
    "entityType": "SelfManagedEntity",
    "globalAssetId": {
      "type": "ExternalReference",
      "keys": [
        {
          "type": "GlobalReference",
          "value": "http://customer.com/demo/asset/1/1/MySubAsset"
        }
      ]
    }
}
----

For a BasicEventElement named “MyBasicEvent”, the Value-Only-payload is minimized to the following:



[source,json,linenums]
----
{
    "observed": {
      "type": "ModelReference",
      "keys": [
        {
          "type": "Submodel",
          "value": "http://customer.com/demo/aas/1/1/1234859590"
        },
        {
          "type": "Property",
          "value": "MaxRotation"
        }
      ]
    }
}
----


=== JSON-Schema for the Value-Only Serialization


The following JSON-Schema represents the validation schema for the ValueOnly-Serialization of submodel elements. This holds true for all submodel elements mentioned in the previous clause except for _SubmodelElementCollections_. Since _SubmodelElementCollections_ are treated as objects containing submodel elements of any kind, the integration into the same validation schema would result in a circular reference or ambiguous results ignoring the actual validation of submodel elements other than _SubmodelElementCollections_. Hence, the same validation schema must be applied for each _SubmodelElementCollection_ within a submodel element hierarchy. In this case, it may be necessary to create a specific JSON-Schema for the individual use case. The _SubmodelElementCollection_ is added to the following schema for completeness and clarity. It is, however, not referenced from the _SubmodelElementValue_-oneOf-Enumeration due to the reasons mentioned above. +
See Annex B for an example that validates against this schema.

[source,json,linenums]
----
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "ValueOnly-Serialization-Schema",
  "$id": "https://admin-shell.io/schema/valueonly/json/V3.0",
  "definitions": {
    "AnnotatedRelationshipElementValue": {
      "type": "object",
      "properties": {
        "first": {
          "$ref": "#/definitions/ReferenceValue"
        },
        "second": {
          "$ref": "#/definitions/ReferenceValue"
        },
        "annotations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ValueOnly"
          }
        }
      },
      "required": [
        "first",
        "second",
        "annotations"
      ],
      "additionalProperties": false
    },
    "BasicEventElementValue": {
      "type": "object",
      "properties": {
        "observed": {
          "$ref": "#/definitions/ReferenceValue"
        }
      },
      "required": [
        "observed"
      ],
      "additionalProperties": false
    },
    "BlobValue": {
      "type": "object",
      "properties": {
        "contentType": {
          "type": "string",
          "minLength": "1",
          "maxLength": "100"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "contentType",
        "value"
      ],
      "additionalProperties": false
    },
    "BooleanValue": {
      "type": "boolean",
      "additionalProperties": false
    },
    "EntityValue": {
      "type": "object",
      "properties": {
        "statements": {
          "$ref": "#/definitions/ValueOnly"
        },
        "entityType": {
          "enum": [
            "SelfManagedEntity",
            "CoManagedEntity"
          ]
        },
        "globalAssetId": {
          "type": "string"
        },
        "specificAssetIds": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SpecificAssetIdValue"
          }
        }
      },
      "required": [
        "statements",
        "entityType"
      ],
      "additionalProperties": false
    },
    "FileValue": {
      "type": "object",
      "properties": {
        "contentType": {
          "type": "string",
          "minLength": "1",
          "maxLength": "100"
        },
        "value": {
          "type": "string",
          "minLength": "1",
          "maxLength": "200"
        }
      },
      "required": [
        "contentType",
        "value"
      ],
      "additionalProperties": false
    },
    "Identifier": {
      "type": "string"
    },
    "Key": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "value"
      ],
      "additionalProperties": false
    },
    "LangString": {
      "type": "object",
      "patternProperties": {
        "^[a-z]{2,4}(-[A-Z][a-z]{3})?(-([A-Z]{2}|[0-9]{3}))?$": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "MultiLanguagePropertyValue": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/LangString"
      },
      "additionalProperties": false
    },
    "NumberValue": {
      "type": "number",
      "additionalProperties": false
    },
	"PropertyValue": {
      "oneOf": [
        {
          "$ref": "#/definitions/StringValue"
        },
        {
          "$ref": "#/definitions/NumberValue"
        },
        {
          "$ref": "#/definitions/BooleanValue"
        }
      ]
    },
    "RangeValue": {
      "type": "object",
      "properties": {
        "min": {
          "type": "number"
        },
        "max": {
          "type": "number"
        }
      },
      "required": [
        "min",
        "max"
      ],
      "additionalProperties": false
    },
    "ReferenceElementValue": {
      "$ref": "#/definitions/ReferenceValue"
    },
    "ReferenceValue": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": ["ModelReference", "ExternalReference"]
        },
        "keys": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Key"
          }
        }
      },
      "additionalProperties": false
    },
    "RelationshipElementValue": {
      "type": "object",
      "properties": {
        "first": {
          "$ref": "#/definitions/ReferenceValue"
        },
        "second": {
          "$ref": "#/definitions/ReferenceValue"
        }
      },
      "required": [
        "first",
        "second"
      ],
      "additionalProperties": false
    },
    "SpecificAssetIdValue": {
      "type": "object",
      "patternProperties": {
        "(.*?)": {
          "type": "string"
        }
      }
    },
    "StringValue": {
      "type": "string",
      "additionalProperties": false
    },
    "SubmodelElementCollectionValue": {
      "$ref": "#/definitions/ValueOnly"
    },
    "SubmodelElementListValue": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/SubmodelElementValue"
      }
    },
    "SubmodelElementValue": {
      "oneOf": [
        {
          "$ref": "#/definitions/BasicEventElementValue"
        },
        {
          "$ref": "#/definitions/RangeValue"
        },
        {
          "$ref": "#/definitions/MultiLanguagePropertyValue"
        },
        {
          "$ref": "#/definitions/FileBlobValue"
        },
        {
          "$ref": "#/definitions/ReferenceElementValue"
        },
        {
          "$ref": "#/definitions/RelationshipElementValue"
        },
        {
          "$ref": "#/definitions/AnnotatedRelationshipElementValue"
        },
        {
          "$ref": "#/definitions/EntityValue"
        },
        {
          "$ref": "#/definitions/PropertyValue"
        },
        {
          "$ref": "#/definitions/SubmodelElementListValue"
        }
      ]
    },
    "ValueOnly": {
      "propertyNames": {
        "pattern": "^[A-Za-z_][A-Za-z0-9_-]*$"
      },
      "patternProperties": {
        "^[A-Za-z_][A-Za-z0-9_-]*$": {
          "$ref": "#/definitions/SubmodelElementValue"
        }
      },
      "additionalProperties": false
    }
  }
}
----