////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////

:imagesdir: ../images/

[appendix]
== Templates for UML Tables

=== General

The templates used for element specification are explained in this annex. For details for the semantics see Legend for UML Modelling.

For capitalization of titles, rules according to https://capitalizemytitle.com/ are used.

=== Template for Classes

Template for Classes:

[.table-with-appendix-table]
[cols="25%h,75%"]
|===
|Class: |<Class Name> [\<<abstract>>] ["\<<Experimental>>"] ["\<<Deprecated>>"] ["\<<Template>>"]
|Explanation: |<Explanatory text>
|Inherits from: |{<Class Name> ";" }+ \| "-"
|===
[cols="25%,40%,25%,10%",options="header"]
|===
|Attribute |Explanation |Type |Card.
|<attribute or association name> ["\<<ordered>>"] ["\<<Experimental>>"] ["\<<Deprecated>>"] |<Explanatory text> |<Type> |<Card>
|===

The following stereotypes can be used:

* \<<abstract>>: Class cannot be instantiated but serves as superclass for inheriting classes
* \<<Experimental>>: Class is experimental, i.e. usage is only recommended for experimental purposes because non backward compatible changes may occur in future versions
* \<<Deprecated>>: Class is deprecated, i.e. it is recommended to not use the element any longer; it will be removed in a next major version of the model
* \<<Template>>: Class is a template only, i.e. class is not instantiated but used for additional specification purposes (for details see parts 3 of document series)
* The following kinds of _Types_ are distinguished:
* _Primitive:_ Type is no object type (class) but a data type; it is just a value
* _Class:_ Type is an object type (class); it is realized as composite aggregation (composition), and does not exist independent of its parent
* _Type:_
** _<Class>:_ Type is a class
** _ModelReference<\{Referable}>:_ Type is a Reference with _Reference/type=ModelReference_ and is called model reference; the \{Referable} is to be substituted by any referable element (including _Referable_ itself for the most generic case) – the element that is referred to is denoted in the __Key/type__=<\{Referable}> for the last _Key_ in the model reference; for the graphical representation see Legend for UML Modelling, Figure 82; for more information on referencing see Clause 5.3.9.
** _<Primitive>: Type_ is a primitive data type, see Clause 5.3.11
** _<Enumeration>:_ Type is an enumeration
* _Card._ is the cardinality (or multiplicity) defining the lower and upper bound of the number of instances of the member element. "*" denotes an arbitrary infinite number of elements of the corresponding Type. "0..1" means optional. "0..*" or "0..3" etc. means that the list may be either not available (null object) or empty.


====
Note 1: attributes having a default value are always considered to be optional; there is always a value for the attribute because the default value is used for initialization in this case.
====



====
Note 2: attributes or attribute elements with data type “string” or “langString” are considered to consist of at least one character.
====



====
Note 3: optional lists, i.e. attributes with cardinality > 1 and minimum 0, are considered to consist of at least one element.
====


[.underline]#Examples for valid model references#

If class type equal to "ModelReference<xref:Submodel[Submodel]>", the following reference would be a valid reference (using the text serialization as defined in Clause 7.2.3):

*(Submodel)https://example.com/aas/1/1/1234859590*

If class type equal to "ModelReference<xref:Referable[Referable]>", the following references would be valid references (using the text serialization as defined in Clause 7.2.3):

*(Submodel)https://example.com/aas/1/1/1234859590*

*(Submodel)https://example.com/aas/1/1/1234859590, (Property)temperature*

*(Submodel)https://example.com/aas/1/1/1234859590, (File)myDocument*

This would be an invalid reference for "ModelReference<xref:Referable[Referable]>", instead type "Reference" shall be used:

*(Submodel)https://example.com/aas/1/1/1234859590, (File)myDocument (FragmentReference)Hints*

This would be an invalid reference for "ModelReference<xref:Submodel[Submodel]>"

*(Submodel)https://example.com/aas/1/1/1234859590, (Property)temperature*

=== Template for Enumerations

Template for Enumerations:

[.table-with-appendix-table]
[cols="30%h,70%"]
|===
|Enumeration: |<Enumeration Name> ["\<<Experimental>>"] ["\<<Deprecated>>"]
|Explanation: |
|Set of: |{<Enumeration> ";" }+ \| "-"
|===
[cols="30%,70%",options="header"]
|===
|Literal |Explanation
|<enumValue1>["\<<Experimental>>"] ["\<<Deprecated>>"] a|
<Explanatory text>

Value of enumeration

|<enumValue2> ["\<<Experimental>>"] ["\<<Deprecated>>"] a|
<Explanatory text>

Value of enumeration, also included in one of the enumerations listed in "Set of:"

|===

"Set Of" lists enumerations that are contained in the enumeration. It is only relevant for validation, making sure that all elements relevant for the enumeration are considered.

Enumeration values use Camel Case notation and start with a small letter. However, there might be exceptions in case of very well-known enumeration values.

=== Template for Primitives

Template for Primitive:

[cols="20%,25%,55%",options="header",]
|===
|*Primitive* |*Explanation* |*Value Examples*
|<Name of Primitive> |<Explanatory text> |Value examples
|===

=== Handling of Constraints

Constraints are prefixed with *AASd-* followed by a three-digit number. The "d" in "AASd-" was motivated by "in Detail". The numbering of constraints is unique within namespace AASd; a number of a constraint that was removed will not be used again.


====
Note: in the Annex listing the metamodel changes, constraints with prefix AASs- or AASc- are also listed. These are security or data specification constraints, and are now part of the split document parts.
====