////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

include::../includes/IDTA-01001_Constraints.adoc[]

:page-partial:

[[spec-constraints]]
=  Constraints: Global Invariants

== Introduction

This clause documents constraints that represent global invariants, i.e. constraints that cannot be assigned to a single class.

In contrast, a class invariant is a constraint that must be true for all instances of a class at any time. They are documented as part of the class specification.

== Constraints for Referables and Identifiables

{aasd117}


=
Note: in other words (AASd-117), __idShort__ is mandatory for all __Referable__s except for referables being direct childs of __SubmodelElementList__s and for all __Identifiable__s.
=


{aasd120}

{aasd022}


=
Note: AASd-022 also means that __idShort__s of referables shall be matched sensitive to the case.
=


== Constraints for Qualifiers

{aasd021}

{aasd119}

{aasd129}

== Constraints for Extensions

{aasd077}

== Constraints for Asset-Related Information

{aasd116}


=
Note: AASd-116 is important to enable a generic search across global and specific asset IDs.
=

=
Note: The semanticId of a SpecificAssetId with the predefined name "gloablAssetId" corresponds to the metamodel attribute "https://admin-shell-io/aas/3/1/AssetInformation/globalAssetId"
=

== Constraints for Types

{aasd130}

Constraint AASd-130 ensures that encoding and interoperability between different serializations is possible. It corresponds to the restrictions as defined for the XML Schema 1.0footnote:[https://www.w3.org/TR/xml/#charsets].

Therefore, we need to restrict an attribute of data type 'string' to the characters that can be represented in any exchange format and language.
Otherwise, strings in other formats such as JSON could not be converted to XML.

The string contains only valid Unicode characters in the range of encoded in UTF-16 format
The character set of XML includes (given as numerical code points and/or ranges in Unicode):
* 0x09: ASCII horizontal tab,
* 0x0A: ASCII linefeed (newline),
* 0x0D: ASCII carriage return.
* 0x20: ASCII space,
* 0x20 - 0xD7FF: all the characters of the Basic Multilingual Plane, and
* 0x00010000-0x0010FFFF: all the characters beyond the Basic Multilingual Plane (*e.g.*, emoticons).

This leads to the following regular expression:
^[\x09\x0A\x0D\x20-\uD7FF\uE000-\uFFFD\u00010000-\u0010FFFF]$

Where:
^: Asserts the start of the string.
[\x09\x0A\x0D\x20-\uD7FF\uE000-\uFFFD\u00010000-\u0010FFFF]: Defines a character class that allows various Unicode characters, with the following elements:

\x09: ASCII horizontal tab.
\x0A: ASCII linefeed (newline).
\x0D: ASCII carriage return.
\x20: ASCII space.
-: Represents a range.
\uD7FF: The upper limit of the Basic Multilingual Plane (BMP) in UTF-16.
\uE000-\uFFFD: Represents the range of characters from the start of the supplementary planes up to the last valid Unicode character (excluding surrogate pairs).
\u00010000-\u0010FFFF: Represents the range of valid surrogate pairs used for characters beyond the BMP.
*: Allows for zero or more occurrences of the characters within the character class.

$: Asserts the end of the string.
