@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/


class Class1 {
}

class Class2 {
}

Class1 "+reverseRelation" ---  "+relation" Class2
@enduml