@startuml
!theme idta from https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/main/plantuml/

class Class1 {
  +attr1: integer = 5
  +attr2: string = "str"
  +attr3: boolean = true
}
@enduml