@startuml
class BasicEventElement<EventElement> <<Experimental>> {
  +observed: Reference
  +direction: Direction
  +state: StateOfEvent
  +messageTopic: MessageTopicType[0..1]
  +messageBroker: Reference[0..1]
  +lastUpdate: dateTime[0..1]
  +minInterval: duration[0..1]
  +maxInterval: duration[0..1]
}
@enduml