@startuml
enum AasNonContainerSubmodelElements <<enumeration>> {
  BasicEventElement
  Blob
  Capability
  DataElement
  EventElement
  File
  MultiLanguageProperty
  Operation
  Property
  Range
  ReferenceElement
  RelationshipElement
}
@enduml