@startuml
enum AasSubmodelElements <<enumeration>> {
  AnnotatedRelationshipElement
  BasicEventElement
  Blob
  Capability
  DataElement
  ContainerElement
  Entity
  EventElement
  File
  MultiLanguageProperty
  Operation
  Property
  Range
  ReferenceElement
  RelationshipElement
  SubmodelElement
  SubmodelElementList
  SubmodelElementCollection
}
@enduml