@startuml
class Qualifier<HasSemantics> {
  +kind: QualifierKind[0..1] <<Experimental>>
  +type: QualifierType
  +valueType: DataTypeDefXsd
  +value: ValueDataType[0..1]
  +valueId: Reference[0..1]
}
@enduml