@startuml
class SubmodelElementList<ContainerElement> {
  +orderRelevant: bool[0..1] = True
  +semanticIdListElement: Reference[0..1]
  +typeValueListElement: AasSubmodelElements
  +valueTypeListElement: DataTypeDefXsd[0..1]
  +value: SubmodelElement[0..*]
}
@enduml