////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////



= Metamodel UML with Inherited Attributes

In this annex, some UML diagrams are shown together with all attributes inherited for a better overview.

.Selected Classes of Metamodel with Inherited Attributes
[plantuml, 89-asset-administration-shell, svg]
....
include::partial$diagrams/89-asset-administration-shell.puml[]
....


====
Note: abstract classes are numbered h0_, h1_ etc.
Their aliases however are defined without this prefix.
The reason for this naming is that no order for inherited classes can be defined in the tooling used for UML modelling (Enterprise Architect); they are ordered alphabetically.
====

.Model for Submodel Elements with Inherited Attributes
[plantuml, 90-submodel-element, svg]
....
include::partial$diagrams/90-submodel-element.puml[]
....
