////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////


[appendix]
= Overview Constraints (non-normative)
include::../includes/constraints.adoc[]


This annex gives an overview of the constraints contained in this document. No additional comments are added, for details please refer to the normative parts of the specification.

For handling of constraints see xref:annex/handling-constraints.adoc[].

{aasd002}
{aasd005}
{aasd006}
{aasd007}
{aasd012}
{aasd014}
{aasd020}
{aasd021}
{aasd022}
{aasd077}
{aasd080}
{aasd081}
{aasd090}
{aasd107}
{aasd108}
{aasd109}
{aasd114}
{aasd115}
{aasd116}
{aasd117}
{aasd118}
{aasd119}
{aasd121}
{aasd122}
{aasd123}
{aasd124}
{aasd125}
{aasd126}
{aasd127}
{aasd128}
{aasd129}
{aasd130}
{aasd131}
{aasd133}
{aasd134}
