name: Check

on: push

jobs:
  Execute:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master

      - name: Install schema-validation
        working-directory: schemas
        run: powershell .\InstallSchemaValidation.ps1

      - name: Validate example data
        working-directory: schemas
        run: powershell .\Validate.ps1
